var app=angular.module("spotnikApp","ui.bootstrap st-auth-module blueimp.fileupload st-common-module seo FacebookPluginDirectives".split(" "));
app.factory("BaseUrlInterceptor",function(){return{request:function(a){"app"==a.url.substring(0,3)||"template"==a.url.substring(0,8)||a.url.match(".html")||a.url.match("http")||(a.url="/api"+a.url);return a}}}).factory("CursorChangeInterceptor",["$q",function(a){return{request:function(a){a.url.match("api")&&!a.url.match("auth")&&$("body").css("cursor","progress");return a},response:function(a){a.config.url.match("api")&&!a.config.url.match("auth")&&$("body").css("cursor","default");return a},responseError:function(b){b.config.url.match("api")&&
!b.config.url.match("auth")&&$("body").css("cursor","default");return a.reject(b)}}}]).config(["$routeProvider","$httpProvider","stAuthInterceptorProvider","AuthProvider","CommonFunctionsProvider","$locationProvider","MetatagsCreatorProvider",function(a,b,d,e,c,f,g){function h(a,b,c,e){var g=a.defer();a=function(a){e?g.resolve(a[e]):g.resolve(a)};c?b(c,a):b(a);return g.promise}f.html5Mode(!1).hashPrefix("!");f={admin:"admin",public:"public",user:"user",company:"company",contest:"contest",thisBrand:{role:"company",
url:"/auth/brand/:brandId"},thisContest:{role:"company",url:"/auth/contest/:contestId"}};var k={possibleTags:["$q","AdService",function(a,b){var c=a.defer(),e=b.getSearchOptions();e.search&&e.filters.tagList?b.fetchPossibleTags(c):c.resolve([]);return c.promise}],possibleBrands:["$q","AdService",function(a,b){var c=a.defer(),e=b.getSearchOptions();e.search&&e.filters.brandList?b.fetchPossibleBrands(c):c.resolve([]);return c.promise}],adBrowserWrapper:["$q","AdService",function(a,b){return h(a,b.getAdsByUrl)}]};
a.when("/",{redirectTo:"/glowna"}).when("/glowna",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k}).when("/reklamy/dodaj",{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",access:"user",resolve:{possibleBrands:["$q","AdService",function(a,b){return h(a,b.getPossibleBrands)}],possibleTags:["$q","AdService",function(a,b){return h(a,b.getPossibleTags)}]}}).when("/reklamy/:adId/:adTitle",{controller:"AdSearchCtrl",
templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:{possibleTags:["$q","AdService",function(a,b){var c=a.defer();c.resolve([]);return c.promise}],possibleBrands:["$q","AdService",function(a,b){var c=a.defer();c.resolve([]);return c.promise}],adBrowserWrapper:["$q","AdService","$route",function(a,b,c){var e=a.defer();b.getAdById(c.current.params.adId,function(a){return e.resolve(a)});return e.promise}]},writeOGMetaTags:!0}).when("/poczekalnia",{controller:"AdSearchCtrl",
templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k}).when("/szukaj",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k}).when("/przegladaj",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,adSearchOptions:{},resolve:k}).when("/losuj/",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,adSearchOptions:{search:!1},
resolve:k}).when("/uzytkownik/:userId/reklamy",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,resolve:k}).when("/konkursy",{controller:"ContestListCtrl",templateUrl:"app/partials/contest/contest-list.html",reloadOnSearch:!1,resolve:{contestsBrowserWrapper:["$q","ContestService","$route",function(a,b,c){return h(a,b.getContestsByUrl)}]}}).when("/konkursy/:contestId/reklamy",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,
adSearchOptions:{filters:{brands:!1}},resolve:k}).when("/konkursy/:contestId/odpowiedzi",{controller:"ContestAnswerListCtrl",templateUrl:"app/partials/contest/contest-answer.html",resolve:{answerBrowserWrapper:["$q","ContestService","$route",function(a,b,c){return h(a,b.getAnswers,c.current.params.contestId)}]}}).when("/konkursy/:contestId/reklamy/dodaj",{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",resolve:{possibleBrands:["$q","AdService","$route","Auth","ContestService",
function(a,b,c,e,g){var d=a.defer();g.fetchContest(c.current.params.contestId,function(a){e.hasRole("company")?b.fetchWistiaProjectId(a.brand.id,function(b){ad.brand.wistiaProjectId=b.response;d.resolve(a)}):d.resolve(a)});return d.promise}],possibleTags:["$q","AdService",function(a,b){return h(a,b.getPossibleTags)}]}}).when("/konkursy/:contestId/odpowiedzi/dodaj",{controller:"ContestAnswerRegistrationCtrl",templateUrl:"app/partials/contest/contest-answer-registration.html",access:f.user}).when("/marki/:brandId/reklamy",
{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",adSearchOptions:{filters:{brands:!1}},resolve:k}).when("/marki/:brandId/reklamy/dodaj",{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",access:"thisBrand",resolve:{possibleBrands:["$q","AdService","$route",function(a,b,c){var e=a.defer();b.fetchWistiaProjectId(c.current.params.brandId,function(a){var b={brand:{}};b.brand.wistiaProjectId=a.response;e.resolve(b)});return e.promise}],possibleTags:["$q",
"AdService",function(a,b){return h(a,b.getPossibleTags)}]}}).when("/reklamy/:parentId/odpowiedz",{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",access:"user",resolve:{possibleBrands:["$q","AdService","$route","Auth",function(a,b,c,e){var g=a.defer();b.getAdsByUrl(function(a){e.hasRole("company")?b.fetchWistiaProjectId(a.brand.id,function(b){a.brand.wistiaProjectId=b.response;g.resolve(a)}):g.resolve(a)});return g.promise}],possibleTags:["$q","AdService",function(a,
b){return h(a,b.getPossibleTags)}]}}).when("/marki/:brandId/konkursy",{controller:"ContestListCtrl",templateUrl:"app/partials/contest/contest-list.html",reloadOnSearch:!1,resolve:{contestsBrowserWrapper:["$q","ContestService","$route",function(a,b,c){return h(a,b.getContestsByUrl)}]}}).when("/marki/:brandId/statystyki",{controller:"BrandStatsCtrl",templateUrl:"app/partials/company/brand-stats.html",resolve:{stats:["$q","CompanyService","$route",function(a,b,c){dateModel={};dateModel.endDate=new Date;
dateModel.startDate=new Date(dateModel.endDate.getFullYear(),dateModel.endDate.getMonth(),1);var e=a.defer();b.getBrandStats(c.current.params.brandId,dateModel,function(a){e.resolve(a)});return e.promise}]}}).when("/konkursy/:contestId/edytuj",{controller:"ContestRegistrationCtrl",templateUrl:"app/partials/contest/contest-registration.html",resolve:{contest:["$q","ContestService","$route",function(a,b,c){return h(a,b.fetchContest,c.current.params.contestId)}]},access:f.thisContest}).when("/uzytkownik/zaloguj",
{controller:"UserLoginCtrl",templateUrl:"app/partials/user/user-login.html"}).when("/marki/:brandId/konkursy/zarejestruj",{controller:"ContestRegistrationCtrl",templateUrl:"app/partials/contest/contest-registration.html",access:"company",resolve:{contest:function(){return null}}}).when("/uzytkownik/zaloguj",{controller:"UserLoginCtrl",templateUrl:"app/partials/user/user-login.html"}).when("/uzytkownik/zarejestruj",{controller:"UserRegistrationCtrl",templateUrl:"app/partials/user/user-registration.html"}).when("/uzytkownik/haslo/przypomnij",
{controller:"PassRecoverCtrl",templateUrl:"app/partials/user/password-recovery.html"}).when("/uzytkownik/haslo/zmien",{controller:"PassChangeCtrl",templateUrl:"app/partials/user/user-change-password.html"}).when("/uzytkownik/:userId/profil",{controller:"UserProfileCtrl",templateUrl:"app/partials/user/profile.html",access:"user",resolve:{profileData:["$q","$http","$rootScope","UserService",function(a,b,c,e){return h(a,e.fetchUserProfile,c.currentUser.id,"response")}]}}).when("/uzytkownik/aktywuj/:token",
{resolve:{activate:["$q","$http","$route","UserService","$location","CommonFunctions",function(a,b,c,e,g,d){var k=a.defer();e.activateUser(c.current.params.token,function(a){a.response?d.pushAlert("success","U\u017cytkownik zosta\u0142 zaaktywowany pomy\u015blnie. Mo\u017cesz si\u0119 teraz zalogowa\u0107"):d.pushAlert("danger","Ten kod aktywacyjny zosta\u0142 u\u017cyty ju\u017c wcze\u015bniej");g.path("/uzytkownik/zaloguj");k.resolve()});return k.promise}]}}).when("/partnerzy/:companyId/aktywuj",
{controller:"CompanyActivateCtrl",templateUrl:"app/partials/confirm-page.html",access:f.admin}).when("/partnerzy/zarejestruj",{controller:"CompanyRegistrationCtrl",templateUrl:"app/partials/company/company-registration.html",access:"user"}).when("/partnerzy/:companyId",{controller:"BrandListCtrl",templateUrl:"app/partials/company/company.html",access:"company",resolve:{brands:["$q","CompanyService","$rootScope",function(a,b,c){if(c.currentUser.companyId)return h(a,b.fetchCompanyBrands,c.currentUser.companyId)}]}}).when("/marki",
{controller:"BrandListCtrl",templateUrl:"app/partials/company/brand-list.html",resolve:{brands:["$q","CompanyService","$rootScope",function(a,b,c){return h(a,b.fetchBrands)}]}}).when("/partnerzy/:companyId/marki/zarejestruj",{controller:"BrandRegistrationCtrl",templateUrl:"app/partials/company/brand-registration.html",access:"company",resolve:{brand:function(){return null}}}).when("/marki/:brandId/edytuj",{controller:"BrandRegistrationCtrl",templateUrl:"app/partials/company/brand-registration.html",
access:"thisBrand",resolve:{brand:["$q","CompanyService","$route",function(a,b,c){return h(a,b.fetchBrand,c.current.params.brandId)}]}}).when("/konkursy/:contestId/:contestName",{controller:"ContestCtrl",templateUrl:"app/partials/contest/contest.html",resolve:{contest:["$q","ContestService","$route",function(a,b,c){return h(a,b.fetchContest,c.current.params.contestId)}]}}).when("/marki/:brandId/:brandName",{controller:"BrandCtrl",templateUrl:"app/partials/company/brand.html",resolve:{brand:["$q",
"CompanyService","$route",function(a,b,c){return h(a,b.fetchBrand,c.current.params.brandId)}]}}).otherwise({redirectTo:"/"});e.setProtectedResourcesList([{url:"/ad",method:"POST",access:"user"},{url:"/ad/*/rate",method:"POST",access:"user"},{url:"/ad/*/state",method:"POST",access:"admin"},{url:"/user/*/password",method:"POST",access:"user"},{url:"/user/*/profile",method:"GET",access:"user"},{url:"/user/*/",method:"POST",access:"user"},{url:"/company",method:"POST",access:"user"},{url:"/company/*/brand",
method:"GET",access:"company"},{url:"/company/*/activate",method:"GET",access:"admin"},{url:"/company/*/brand",method:"POST",access:"company"},{url:"/brand/*",method:"POST",access:"company"},{url:"/brand/*/contest",method:"POST",access:"company"},{url:"contest/*",method:"POST",access:"company"},{url:"/contest/*/answer",method:"POST",access:"user"},{url:"/contest/*/answer",method:"GET",access:"contest"},{url:"/auth/*",method:"GET",access:"user"},{url:"/user/login/status",method:"GET",access:"user"}]);
e.setUserRoles(f);d.setLoginUrl("/uzytkownik/zaloguj");b.interceptors.push("BaseUrlInterceptor");b.interceptors.push("CursorChangeInterceptor");b.interceptors.push("stAuthInterceptor");c.setWordMappings({uzytkownik:"user",konkursy:"contest",reklamy:"ad",losuj:"ad/rand",poczekalnia:"ad?place\x3d1",szukaj:"ad",glowna:"ad?place\x3d0",przegladaj:"ad",marki:"brand",odpowiedz:""});g.setDefaultMetatags({url:"http://www.spotnik.pl/#!/glowna",description:"Spotnik.pl - reklamy, \u015bmieszne spoty reklamowe!",
title:"Spotnik.pl - reklamy nie musz\u0105 by\u0107 nudne!",type:"website",image:"http://www.spotnik.pl/resources/img/logo.png",site_name:"Spotnik.pl"})}]).run(["$rootScope","$location","Auth","CommonFunctions","$q","MetatagsCreator",function(a,b,d,e,c,f){function g(a){if(!a)return d.isLoggedIn()?e.pushAlertByType("accessDenied"):(e.pushAlertByType("login"),b.path("/uzytkownik/zaloguj")),c.reject()}a.$on("$routeChangeStart",function(a,b,e){if(b.$$route&&b.$$route.access){a=d.isAuthorized(b.$$route.access,
b.params);var f=c.when(a);f.then(g,g);b.resolve=b.resolve||{};angular.extend(b.resolve,{__authentication__:function(){return f}})}})}]);app.controller("AdSearchCtrl",["$scope","filterFilter","$location","CommonFunctions","AdService","$http","possibleTags","possibleBrands","adBrowserWrapper",function(a,b,d,e,c,f,g,h,k){function m(a,b){var c=""+b,e=$.inArray(c,a);0<=e?a.splice(e,1):a.push(c)}function l(){c.getAdsByUrl(function(b){b.ads?(a.model.ads=b.ads,a.total=b.total):a.model.ads=[b]})}function p(){a.searchOptions.filters.rank&&a.$watchCollection("filters.rankFrom + filters.rankTo",function(){a.text.rank=n(a.filters.rankFrom,a.filters.rankTo)},
!0);a.searchOptions.filters.year&&a.$watchCollection("filters.yearFrom + filters.yearTo",function(){a.text.year=n(a.filters.yearFrom,a.filters.yearTo)},!0);a.searchOptions.filters.votes&&a.$watchCollection("filters.votesFrom + filters.votesTo",function(){a.text.votes=n(a.filters.votesFrom,a.filters.votesTo)},!0);a.searchOptions.filters.place&&a.$watch("filters.place",function(b){a.text.place="";angular.forEach(a.possiblePlaces,function(c){""!==b&&b==c.value&&(a.text.place=c.label)})},!0)}function n(a,
b){if(void 0===a||null==a||0==a.length)a="";if(void 0===b||null==b||0==b.length)b="";return""==a&&""!=b?"poni\u017cej "+b:""!=a&&""==b?"powy\u017cej "+a:""==a&&""==b?"":a+" - "+b}a.search=function(){var b=a.filters;$.each(b,function(a,c){void 0!==c&&null!=c&&0!=c.length||delete b[a]});d.search(b)};a.changeOrder=function(b){a.filters.orderBy=b;a.filters.order="asc"==a.filters.order?"desc":"asc"};a.isInBrandList=function(b){return 0<=$.inArray(""+b.id,a.helper.brandArr)?!0:!1};a.toogleBrand=function(b){m(a.helper.brandArr,
b)};a.isInTagList=function(b){return 0<=$.inArray(""+b.id,a.helper.tagArr)?!0:!1};a.toogleTag=function(b){m(a.helper.tagArr,b)};a.$on("$routeUpdate",function(b){a.filters=d.search();l()});a.selectPage=function(b){a.filters.page=b;a.search()};(function(){a.filters=d.search();a.helper={};a.helper.brandArr=[];a.helper.tagArr=[];a.text={};a.possibleTags=g||[];a.possibleBrands=h||[];a.possiblePlaces=[{label:"Poczekalnia",value:1},{label:"G\u0142\u00f3wna",value:0}];a.model={};a.searchOptions=c.getSearchOptions();
a.$watch("filters.brandList",function(b){a.helper.brandArr=b?b.split(","):[]});a.$watchCollection("helper.brandArr",function(b){b&&(a.filters.brandList=b.join(","))});a.$watch("filters.tagList",function(b){a.helper.tagArr=b?b.split(","):[]});a.$watchCollection("helper.tagArr",function(b){b&&(a.filters.tagList=b.join(","))});p();void 0!==k.total?(a.model.ads=k.ads,a.total=k.total):(a.model.ads=[k],a.model.singleAd=k)})()}]);
app.controller("RatingCtrl",["$scope","AdService","$timeout",function(a,b,d){(function(){a.max=5;a.isReadonly=!1;a.adModel.tooltip.ranked=!1;a.rate=Math.floor(a.ad.rank);a.labelValue=Math.floor(a.ad.rank);a.hoveringOver=function(b){a.overStar=b;a.labelValue=b};a.onLeave=function(){a.labelValue=Math.floor(a.ad.rank);a.overStar=null;a.rate=Math.floor(a.ad.rank)};a.$watch("rate",function(e){a.overStar&&b.rate(a.$parent.ad.id,e,function(){a.$emit("RANKED","ranked")})});a.$watch("ad.rank",function(b){a.rate=
Math.floor(a.ad.rank);a.labelValue=Math.floor(a.ad.rank)});a.ratingStates=[{stateOn:"icon-star icon-large",stateOff:"icon-star-empty icon-large"}]})()}]);
app.controller("AdRegistrationCtrl",["$scope","possibleBrands","possibleTags","$modal","filterFilter","ErrorFactory","$location","AdService","Auth","$routeParams",function(a,b,d,e,c,f,g,h,k,m){var l=a.$new(),p=null,n=a.$new(),q=null;(function(){a.regModel={};a.regModel.tags=[];a.selectedTags="";a.possibleTags=d||[];a.yearMax=(new Date).getFullYear();a.errorMessages=f.getErrorMessages({pattern:{url:"Tylko prawid\u0142owe linki youtube"}});a.companyUser=k.hasRole("company");m.contestId&&(a.regModel.contestId=
m.contestId,a.regModel.brandId=b.brand.id);m.parentId&&(a.regModel.parentId=m.parentId,a.regModel.brandId=b.brand.id);m.brandId&&(a.regModel.brandId=m.brandId);if(a.companyUser){var c=b.brand.wistiaProjectId;m.parentId||m.contestId?a.$watch("regModel.videoId",function(b){a.regModel.videoId&&h.postAd(a.regModel,function(b){g.path("/reklamy/"+b.response+"/"+a.regModel.title.replace(/ /g,"-"))})}):a.$watch("regModel.videoId",function(b){a.regModel.videoId&&h.postBrandAd(a.regModel.brandId,a.regModel,
function(b){g.path("/marki/"+a.regModel.brandId+"/reklamy")})});new wistia.UploadWidget({divId:"wistia-upload-widget",publicProjectId:c,buttonText:"Dodaj reklam\u0119",callbacks:{uploadSuccess:function(b){a.regModel.videoId=b.hashed_id;a.regModel.thumbnail=b.thumbnail.url;a.regModel.duration=Math.floor(b.duration);a.$apply()},fileQueued:function(a){a=a.name.split(".").pop().toLowerCase();-1==$.inArray(a,"mov mpg avi flv f4v mp4 m4v asf wmv vob mod 3gp mkv divx xvid".split(" "))?(this.cancelUpload(),
this.reset(),$(".upload-status").addClass("hidden"),$("#upload-file-error").html("Tylko pliki z ro\u017cszerzeniem mov, mpg, avi, flv, f4v, mp4, m4v, asf, wmv, vob, mod, 3gp, mkv, divx, xvid"),$("#upload-file-error").removeClass("hidden")):($(".upload-status").removeClass("hidden"),$("#upload-file-error").addClass("hidden"))}}})}else a.possibleBrands=b||[],l.items=b,l.title="Wybierz mark\u0119",l.type=0,a.openBrandsModal=function(){p=e.open({templateUrl:"tagsBrandsPickerModal.html",scope:l})},l.click=
function(b){a.selectedBrandName=b.name;a.regModel.brandId=b.id;p.close()};n.items=d;n.title="Wybierz kategorie";n.type=1;a.openTagsModal=function(){q=e.open({templateUrl:"tagsBrandsPickerModal.html",scope:n})};n.ok=function(){q.close()};a.register=function(){h.postAd(a.regModel,function(b){g.path("reklamy/"+b.response+"/"+a.regModel.title.replace(/ /g,"-"))})};a.click=function(b,c){b.selected=!b.selected;if(b.selected)a.regModel.tags.push(b.id);else{var e=a.regModel.tags.indexOf(b.id);a.regModel.tags.splice(e,
1)}a.selectedTags=a.regModel.tags.join();c&&c.stopPropagation()}})()}]);app.controller("TopAdsCtrl",["$scope","AdService",function(a,b){(function(){a.model={};b.getAds({orderBy:"rank",order:"desc",page:"1"},function(b){a.model.topAds=b.ads});a.roundRank=function(a){return Math.floor(a)}})()}]);
app.controller("AdAdminPanelCtrl",["$scope","AdService",function(a,b){(function(){a.model={};a.changePlace=function(a,e,c){b.changeState(a.id,{place:e},function(b){a.place=c})};a.changeApproved=function(a){b.changeState(a.id,{approved:!a.approved},function(b){a.approved=!a.approved})};a.changeAgeProtected=function(a){b.changeState(a.id,{ageProtected:!a.ageProtected},function(b){a.ageProtected=!a.ageProtected})}})()}]);
app.controller("AdCtrl",["$scope","AdService","$rootScope","$route","$location","$timeout",function(a,b,d,e,c,f){(function(){a.adModel={};a.adModel.tooltip={};a.tooltip={};a.reportAbuse=function(){b.reportAbuse(a.ad.id,a.adModel.abuseMessage,function(){a.$emit("REPORT_ABUSE");a.adModel.abuseMessage="";f(function(){a.bottomVideoPanelView=""},1E3)})};e.current.$$route.writeOGMetaTags&&(a.metatags.title="Spotnik.pl - reklamy: "+a.ad.title,a.metatags.description=a.ad.description.substring(0,160),a.metatags.image=
a.ad.videoData.bigThumbnail,a.metatags.url="http://www.spotnik.pl/#!/reklamy/"+a.ad.id+"/"+a.ad.title.replace(/ /g,"-"))})()}]);app.controller("SearchInputCtrl",["$scope","$location",function(a,b){(function(){a.model={};a.search=function(){b.path("/szukaj/");b.search({});b.search(a.model)}})()}]);app.controller("CompanyRegistrationCtrl",["CompanyService","$location","$scope","$rootScope","ErrorFactory","CommonFunctions",function(a,b,d,e,c,f){(function(){d.regModel={};d.regModel.address={};d.errorMessages=c.getErrorMessages({});d.register=function(){a.register(d.regModel,function(a){f.pushAlert("success","Dzi\u0119kujemy za ch\u0119\u0107 wsp\u00f3\u0142pracy z nami. W ci\u0105gu 24h otrzymasz od nas email z dalszymi instrukcjami.");b.path("/")},function(a,b){443==b&&f.pushAlert("danger","Ju\u017c wcze\u015bniej wyrazi\u0142e\u015b/\u0142a\u015b ch\u0119\u0107 wsp\u00f3\u0142pracy z nami. Je\u015bli nie dosta\u0142e\u015b/\u0142a\u015b od nas wiadomo\u015bci w ci\u0105gu 24h od rejestracji skontaktuj si\u0119 z nami.")})}})()}]);
app.controller("CompanyActivateCtrl",["$routeParams","CompanyService","$location","CommonFunctions","$scope",function(a,b,d,e,c){(function(){c.message="Czy chcesz aktywowa\u0107 firm\u0119.";c.cancel=function(){d.path("/")};c.ok=function(){b.activateCompany(a.companyId,function(a){a.response?e.pushAlert("success","Firma zosta\u0142a zaaktywowana pomy\u015blnie."):e.pushAlert("success","Firma ju\u017c wcze\u015bniej zosta\u0142a zaaktywowana.");d.path("/")})}})()}]);
app.controller("BrandListCtrl",["brands","$scope",function(a,b){b.brands=a}]);app.controller("BrandStatsCtrl",["stats","$scope","CompanyService","$routeParams",function(a,b,d,e){(function(){b.wistiaStats=a;b.dateModel={};b.getStats=function(){d.getBrandStats(e.brandId,b.dateModel,function(a){b.wistiaStats=a})}})()}]);app.controller("BrandCtrl",["brand","$scope",function(a,b){b.brand=a}]);
app.controller("BrandRegistrationCtrl",["$scope","ErrorFactory","$location","$routeParams","CompanyService","brand","Auth",function(a,b,d,e,c,f,g){(function(){a.regModel={};a.errorMessages=b.getErrorMessages({});f?(a.regModel.name=f.name,a.regModel.description=f.description,a.locationEdit=!0,a.brand=f,a.submitText="Zaktualizuj",a.options={url:"/api/brand/"+e.brandId+"/upload/image",type:"POST",dataType:"json",headers:{},autoUpload:!0},$.extend(a.options.headers,g.getAuthHeader()),$("#fileupload").bind("fileuploaddone",
function(b,c){a.brand.smallLogoUrl=c.result.small;a.brand.logoUrl=c.result.big}),a.register=function(){c.updateBrand(e.brandId,a.regModel,function(b){d.path("/marki/"+e.brandId+"/"+a.regModel.name.replace(/ /g,"-"))})}):(a.register=function(){c.registerBrand(e.companyId,a.regModel,function(a){d.path("/marki/"+a.response+"/edytuj")})},a.submitText="Dodaj mark\u0119")})()}]);app.controller("ContestListCtrl",["contestsBrowserWrapper","$scope","$location","ContestService","$routeParams",function(a,b,d,e,c){function f(){e.getContestsByUrl(function(a){b.total=a.total;b.contests=a.contests})}(function(){b.filters=d.search();b.contests=a.contests;b.total=a.total;b.selectPage=function(a){b.filters.page=a;d.search(b.filters)};b.$on("$routeUpdate",function(a){b.filters=d.search();f()})})()}]);
app.controller("ContestAnswerListCtrl",["answerBrowserWrapper","$scope","$routeParams","ContestService",function(a,b,d,e){(function(){b.contestAnswers=a.contestAnswers;b.total=a.total;b.currentPage=1;b.selectPage=function(a){b.filters.page=a;b.search()};b.pressWinner=function(a){e.updateWinner(d.contestId,a.id,!a.winner,function(b){a.winner=!a.winner})}})()}]);
app.controller("ContestAnswerRegistrationCtrl",["ContestService","$scope","$routeParams","ErrorFactory","$location","CommonFunctions",function(a,b,d,e,c,f){(function(){b.regModel={};b.errorMessages=e.getErrorMessages({});b.submit=function(){a.registerAnswer(d.contestId,b.regModel,function(a){f.pushAlert("success","Twoja odpowied\u017a zosta\u0142a zarejestrowana");c.path("/konkursy/"+d.contestId+"/")},function(a,b){442==b?f.pushAlert("danger","Konkurs ju\u017c si\u0119 zako\u0144czy\u0142"):443==
b&&f.pushAlert("danger","Ju\u017c wcze\u015bniej doda\u0142e\u015b/a\u015b odpowied\u017a")})}})()}]);app.controller("ContestCtrl",["contest","$scope",function(a,b){b.contest=a}]);
app.controller("ContestRegistrationCtrl",["$scope","ErrorFactory","$location","$routeParams","ContestService","$filter","contest",function(a,b,d,e,c,f,g){function h(){var b=angular.copy(a.regModel);b.finishDate=new Date(b.finishDate.date.getFullYear(),b.finishDate.date.getMonth(),b.finishDate.date.getDate(),b.finishDate.time.getHours(),b.finishDate.time.getMinutes(),b.finishDate.time.getSeconds());b.scoresDate=new Date(b.scoresDate.date.getFullYear(),b.scoresDate.date.getMonth(),b.scoresDate.date.getDate(),
b.scoresDate.time.getHours(),b.scoresDate.time.getMinutes(),b.scoresDate.time.getSeconds());return b}(function(){a.regModel={};a.regModel.scoresDate={};a.regModel.finishDate={};a.minDate=new Date;a.errorMessages=b.getErrorMessages({dateValid:{scoresDate:"Data musi by\u0107 po\u017aniejsza",finishDate:"Data musi by\u0107 po\u017aniejsza"}});g?(a.regModel.name=g.name,a.regModel.description=g.description,a.regModel.finishDate.date=new Date(g.finishDate),a.regModel.finishDate.time=new Date(g.finishDate),
a.regModel.scoresDate.date=new Date(g.scoresDate),a.regModel.scoresDate.time=new Date(g.scoresDate),a.regModel.type=g.type,a.register=function(){var a=h();c.updateContest(e.contestId,a,function(b){d.path("/konkursy/"+e.contestId+"/"+a.name.replace(/ /g,"-"))})}):(a.regModel.finishDate.time=new Date,a.regModel.scoresDate.time=new Date,a.register=function(){var a=h();c.registerContest(e.brandId,a,function(b){d.path("/konkursy/"+b.response+"/"+a.name.replace(/ /g,"-"))})});a.minDate=new Date;a.$watchCollection("regModel.finishDate",
function(b){b.date&&b.time&&a.contestRegForm.finishDate&&(new Date(b.date.getFullYear(),b.date.getMonth(),b.date.getDate(),b.time.getHours(),b.time.getMinutes(),b.time.getSeconds())<=new Date(new Date+9E5)?a.contestRegForm.finishDate.$setValidity("dateValid",!1):a.contestRegForm.finishDate.$setValidity("dateValid",!0))});a.$watchCollection("regModel.finishDate",function(b){b.date&&b.time&&a.contestRegForm.finishDate&&(new Date(b.date.getFullYear(),b.date.getMonth(),b.date.getDate(),b.time.getHours(),
b.time.getMinutes(),b.time.getSeconds())<=new Date+9E5?a.contestRegForm.scoresDate.$setValidity("dateValid",!1):a.contestRegForm.scoresDate.$setValidity("dateValid",!0))})})()}]);app.controller("UserLoginCtrl",["$scope","ErrorFactory","Auth","$location",function(a,b,d,e){a.loginModel={};a.login=function(){d.login(a.loginModel,function(){e.path("/")})}}]);
app.controller("UserProfileCtrl",["$scope","$location","profileData","$http","CommonFunctions","$routeParams","Auth",function(a,b,d,e,c,f,g){a.profileModel=d;a.update=function(){e.post("/user/"+a.currentUser.id+"/",a.profileModel).success(function(){c.pushAlert("success","Dane u\u017cytkownika zosta\u0142y zaktualizowane")})};a.options={url:"/api/user/"+f.userId+"/upload/image",type:"POST",dataType:"json",headers:{},autoUpload:!0};$.extend(a.options.headers,g.getAuthHeader());$("#fileupload").bind("fileuploaddone",
function(a,b){g.changeUser({imageUrl:b.result.response})})}]);
app.controller("PassRecoverCtrl",["$scope","$location","$http","CommonFunctions","ErrorFactory","UserService",function(a,b,d,e,c,f){a.recoverModel={};a.errorMessages=c.getErrorMessages({});a.recover=function(){f.recoverPassword(a.recoverModel.email,function(c){c.response?e.pushAlert("success","Wys\u0142ali\u015bmy has\u0142o na podany adres email: "+a.recoverModel.email):e.pushAlert("danger","Podany adres email: "+a.recoverModel.email+" nie istnieje w naszej bazie.");b.path("/uzytkownik/zaloguj")})}}]);
app.controller("PassChangeCtrl",["$scope","$location","$http","CommonFunctions","ErrorFactory","$rootScope",function(a,b,d,e,c,f){a.changePassModel={};a.errorMessages=c.getErrorMessages({});a.change=function(){d.post("/user/"+f.currentUser.id+"/password",a.changePassModel).success(function(c){c.response?(e.pushAlert("success","Has\u0142o zosta\u0142o zmienione"),b.path("/")):(e.pushAlert("danger","Nieprawid\u0142owe has\u0142o"),a.changePassModel.oldPassword="")})}}]);
app.controller("UserRegistrationCtrl",["$scope","ErrorFactory","$locale","$location","$http","CommonFunctions","$filter",function(a,b,d,e,c,f,g){(function(){a.regModel={};a.errorMessages=b.getErrorMessages({pattern:{username:"Tylko litery i cyfry"},unique:{username:"Taki u\u017cytkownik ju\u017c istnieje",email:"Taki adres email ju\u017c istnieje"}});a.months=d.DATETIME_FORMATS.MONTH;a.register=function(){var b=angular.copy(a.regModel);b.birthdate=("0"+a.regModel.birthdate.year).slice(-4)+"-"+("0"+
a.regModel.birthdate.month).slice(-2)+"-"+("0"+a.regModel.birthdate.day).slice(-2);c({method:"POST",url:"/user",data:b}).success(function(b){f.pushAlert("success","U\u017cytkownik zosta\u0142 zarejestrowany. Prosimy o potwierdzenie rejestracji poprzez klikni\u0119cie w link kt\u00f3ry wys\u0142ali\u015bmy na podany adres email: "+a.regModel.mail);e.path("/uzytkownik/zaloguj")})}})()}]);
app.controller("UserDropdownCtrl",["$scope","Auth","$location",function(a,b,d){a.logout=function(){b.logout();d.path("/")};a.showProfile=function(){d.path("/uzytkownik/"+a.currentUser.id+"/profil")}}]);app.directive("wistiaEmbedded",["$http",function(a){return{restrict:"A",link:function(b,d,e){b="http://fast.wistia.com/oembed.json?url\x3d"+encodeURIComponent("http://home.wistia.com/medias/"+b.ad.videoData.videoId+"?embedType\x3dseo\x26videoWidth\x3d620\x26videoHeight\x3d349");a.get(b).success(function(a){d.html("");a=a.html.replace('\x3cscript charset\x3d"ISO-8859-1" src\x3d"//fast.wistia.com/assets/external/E-v1.js"\x3e\x3c/script\x3e',"");d.append(a)})}}}]);
app.directive("embedSrc",function(){return{restrict:"A",link:function(a,b,d){var e=b;a.$watch(function(){return d.embedSrc},function(){var a=b.clone().attr("src",d.embedSrc);e.replaceWith(a);e=a})}}});app.directive("stSubmit",["$parse",function(a){return{restrict:"A",require:["stSubmit","?^form"],controller:["$scope",function(a){this.attempted=!1;var d=null;this.setAttempted=function(){this.attempted=!0};this.setFormController=function(a){d=a};this.needsAttention=function(a){return d?a?a.$invalid&&this.attempted:d&&d.$invalid&&(d.$dirty||this.attempted):!1}}],compile:function(b,d,e){return{pre:function(a,b,e,d){b=d[0];b.setFormController(1<d.length?d[1]:null);a.st=a.st||{};a.st[e.name]=b;a.st.busy=
[]},post:function(b,e,g,d){var k=d[0],m=1<d.length?d[1]:null,l=a(g.stSubmit);e.bind("submit",function(){k.setAttempted();b.$$phase||b.$apply();if(!m.$valid||0<b.st.busy.length)return!1;e.find(":submit").attr("disabled",!0);b.$apply(function(){l(b,{$event:event})})})}}}}}]);
app.directive("stError",function(){return{restrict:"A",require:"^form",link:function(a,b,d,e){var c=$("[name\x3d"+e.$name+"]").find("[name\x3d"+d.stError+"]"),f=d.stErrorMessagesVar?d.stErrorMessagesVar:"errorMessages";a.$watchCollection(e.$name+"."+d.stError+".$error",function(e){var h=!1;angular.forEach(e,function(e,g){if(e){var l=a[f][g],p=null;l&&(p=l[d.stError]?l[d.stError]:l.def,p.match("{{.*}}")&&(l=p.match("{{.*}}","g"),$.each(l,function(a,b){b=b.replace(RegExp("{","g"),"").replace(RegExp("}",
"g"),"");c.attr(b)&&(p=p.replace("{{"+b+"}}",c.attr(b)))})),b.removeClass("hidden"),b.text(p));h=!0}});h||b.addClass("hidden")},!0)}}});app.directive("stFieldMatch",["$parse",function(a){return{require:"ngModel",link:function(b,d,e,c){c.$setValidity("fieldMatch",!1);b.$watch(function(){return a(e.stFieldMatch)(b)===c.$modelValue},function(a){c.$setValidity("fieldMatch",a);c.$dirty=!0})}}}]);
app.directive("stDateValidation",["$parse",function(a){return{require:"ngModel",link:function(a,d,e,c){c.$setValidity("dateValid",!1);var f=/^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$/i;a.$watchCollection(e.stDateValidation,
function(a){a&&a.day&&a.month&&a.year?(a=("0"+a.day).slice(-2)+"."+("0"+a.month).slice(-2)+"."+a.year,a=f.test(a),c.$setValidity("dateValid",a)):c.$setValidity("dateValid",!1);c.$dirty=!0})}}}]);app.filter("stErrorMessagesFilter",function(){return function(a,b){var d={};angular.forEach(a,function(a,c){a==b&&(d[c]=a)});return d}});
app.directive("stActive",["$location",function(a){return{restrict:"A",link:function(b,d,e){b.$on("$routeChangeSuccess",function(b,e,g){$.each(d.children("li"),function(b,c){var e=$(c),d=e.children("a");d&&$(d).attr("href")&&($(d).attr("href").replace("#!","")===a.path()?e.addClass("active"):e.removeClass("active"))})})}}}]);
app.directive("stEnsureUnique",["Auth","$timeout",function(a,b){return{restrict:"A",require:"ngModel",link:function(d,e,c,f){var g;d.$watch(function(){return f.$modelValue},function(e){e&&(b.cancel(g),g=b(function(){d.st.busy.push(c.name);a[c.name+"Exist"](e,function(a){f.$setValidity("unique",!a);f.$dirty=!0;d.st.busy.splice(d.st.busy.indexOf(c.name),1)})},200))})}}}]);
app.directive("numbersOnly",function(){return{require:"ngModel",link:function(a,b,d,e){e.$parsers.push(function(a){if(void 0==a)return"";var b=a.replace(/[^0-9]/g,"");b!=a&&(e.$setViewValue(b),e.$render());return b})}}});
app.directive("stValidFormElem",function(){return{restrict:"A",require:"^form",replace:!0,transclude:!0,scope:!0,templateUrl:"app/partials/valid-form-elem.html",compile:function(a,b,d){return{pre:function(a,b,d,g){a.stForm=a[g.$name];a.stFormName=g.$name;a.stLabel=d.stLabel;a.stName=d.stName;a.stIcon=d.stIcon;a.stInputGroup=a.$eval(d.stInputGroup);void 0===a.stInputGroup&&(a.stInputGroup=!0)}}}}});
app.directive("ngFocus",["$parse",function(a){return function(b,d,e){var c=a(e.ngFocus);d.bind("focus",function(a){b.$apply(function(){c(b,{$event:a})})})}}]);angular.module("st-common-module",["ngCookies","angularLocalStorage"]).controller("PagingCtrl",["$scope","$location",function(a,b){a.filters.page=parseInt(a.filters.page)||1;a.$watch("filters.page",function(b){a.currentPage=parseInt(a.filters.page)||1;window.scrollTo(0,0)})}]).provider("CommonFunctions",function(){var a=this;this.wordMappings={};this.setWordMappings=function(a){this.wordMappings=a};this.$get=["$rootScope","$location","$timeout",function(b,d,e){b.alerts=[];b.closeAlert=function(a){b.alerts.splice(a,
1)};return{pushAlert:function(a,d){var g=b.alerts.push({type:a,msg:d});e(function(){b.alerts.splice(g-1)},5E3)},pushAlertByType:function(a){switch(a){case "login":this.pushAlert("danger","Musisz si\u0119 najpierw zalogowa\u0107.");break;case "accessDenied":this.pushAlert("danger","Nie masz wystarczaj\u0105cych uprawnie\u0144.");break;case "badRequest":this.pushAlert("danger","Ups, co\u015b posz\u0142o nie tak. Prosz\u0119, post\u0119puj zgodnie z podpowiedziami")}},getPostHeader:function(){return{headers:{"Content-Type":"application/x-www-form-urlencoded"}}},
translateWord:function(b){return a.wordMappings[b]},translateUrl:function(a){a=a.split("/");""==a[0]&&delete a[0];var b="/",e=this;angular.forEach(a,function(a){var c=e.translateWord(a);""==c?b+=c:(b+=c||a,b+="/")});1<b.length&&(b=b.slice(0,b.length-1));return b},getTranslatedUrl:function(){return this.translateUrl(d.path())}}}]}).factory("ErrorFactory",function(){this.errorMessages={pattern:{def:"Niew\u0142a\u015bciwe znaki"},minlength:{def:"Min {{data-ng-minlength}} znak\u00f3w"},maxlength:{def:"Max {{data-ng-maxlength}} znak\u00f3w"},
fieldMatch:{def:"Pola nie s\u0105 takie same"},email:{def:"Niepoprawny email"},dateValid:{def:"Niepoprawna data"},min:{def:"Podana liczba musi by\u0107 wi\u0119ksza od {{data-min}}"},max:{def:"Podana liczba musi by\u0107 mniejsza od {{data-max}}"}};this.getErrorMessages=function(a){return $.extend(!0,this.errorMessages,a)};return this}).directive("stTimeoutTooltip",["$animator","$timeout",function(a,b){return{restrict:"A",link:function(a,e,c){a.$on(c.stOn,function(){e.addClass("in");b(function(){e.removeClass("in")},
c.timeout)})}}}]).directive("stHref",function(){return{restrict:"A",link:function(a,b,d){d.$observe("stHref",function(a){b.attr("href",a.replace(/ /g,"-"))})}}}).directive("stNewWindow",function(){return{restrict:"A",link:function(a,b,d){var e=d.width?d.width:650,c=d.height?d.height:350;b.bind("click",function(a){a.preventDefault();window.open(d.href||d.stHref,"newwindow","width\x3d"+e+", height\x3d"+c+", left\x3d"+(screen.width/2-e/2)+", top\x3d"+(screen.height/2-c/2))})}}}).provider("MetatagsCreator",
function(){var a={};this.setDefaultMetatags=function(b){a=b};this.$get=["$rootScope",function(b){b.metatags=a}]});
(function(){var a,b,d,e,c,f;b=angular.module("FacebookPluginDirectives",[]);a=function(a){return b.directive(a,["$timeout",function(a){return{restrict:"C",compile:function(b,c,e){return{post:function(b,c,e,d){b.$watch("ad.id",function(){a(function(){return"undefined"!==typeof FB&&null!==FB?FB.XFBML.parse(c.parent()[0]):void 0},50,!1)})}}}}}])};f="fbActivity fbComments fbFacepile fbLike fbLikeBox fbLiveStream fbLoginButton fbName fbProfilePic fbRecommendations".split(" ");e=0;for(c=f.length;e<c;e++)d=
f[e],a(d)}).call(this);var test=angular.module("st-auth-module-test",["ngMockE2E"]);
test.run(function(a){a.whenGET(/app\/partials\/.*/).passThrough();a.whenPOST("/user/username").passThrough();a.whenPOST("/user/email").passThrough();a.whenGET(/\/ad.*/).passThrough();a.whenGET(/\/uzytkownik\/11\/reklamy/).respond([{title:"Bmw reklama",videoUrl:"http://youtu.be/4KVVDdnGtdM",user:{displayName:"maniekstasz",imageUrl:"resources/static/no-user.gif"},creationDate:"1382523642",description:"adsfasdfasdfasdfasdfasfsdfasdf",rank:"3.75"}]);a.whenGET("/tag").respond([{name:"napoje",selected:!1,
id:5},{name:"piwa",selected:!1,id:2},{name:"soki",selected:!1,id:1}]);a.whenGET("/brand").respond([{name:"Coca cola",selected:!1,id:2},{name:"Coca cola",selected:!1,id:2},{name:"BMW",selected:!1,id:3}]);a.whenGET("http://localhost:8080/user/username").passThrough();a.whenPOST("/user/email").passThrough();a.whenPOST("/user/login").respond({displayName:"maniekstasz",imageUrl:"asdf",roles:["user"],authToken:"asdfasfasewqrzxdxzcivqqrqwevrwqejdjfl",id:"11"});a.whenPOST("/ad/rate").respond({rank:"4.75"});
a.whenPOST("/user/password/recover").respond({});a.whenPOST("/user/password/change").respond({});a.whenPOST("/user").respond(!0)});angular.module("st-auth-module",["ngCookies","angularLocalStorage","st-common-module"]).provider("Auth",function(){var a=this;this.loginUrl="/user/login";this.userStatusUrl="/user/login/status";this.usernameExistUrl="/user/username";this.emailExistUrl="/user/email";this.userRoles={public:"public",user:"user",admin:"admin"};this.protectedResourcesList=[];this.setProtectedResourcesList=function(a){angular.forEach(a,function(a){a.url=a.url.replace(/\//g,"\\/").replace(/\*/g,"[^ ]*");a.url=RegExp("^/api"+
a.url+"$","i")});this.protectedResourcesList=a};this.setLoginUrl=function(a){this.loginUrl=a};this.setUserStatusUrl=function(a){this.userStatus=a};this.setUserRoles=function(a){this.userRoles=a};this.setUsernameExistUrl=function(a){this.usernameExistUrl=a};this.setEmailExistUrl=function(a){this.emailExistUrl=a};this.$get=["$injector","$cookieStore","storage","$rootScope",function(b,d,e,c){c.currentUser=e.get("loggedInUser")||{roles:[this.userRoles.public]};var f=!1;return{setDeleteTokens:function(){f=
!0},usernameExist:function(c,e,d){b.get("$http")({method:"GET",url:a.usernameExistUrl+"?username\x3d"+c}).success(function(a){e(a.response)}).error(d)},emailExist:function(c,e,d){b.get("$http")({method:"GET",url:a.emailExistUrl+"?email\x3d"+c}).success(function(a){e(a.response)}).error(d)},login:function(d,h,k){k=b.get("$http");f&&(d.deleteTokens=!0);k.post(a.loginUrl,$.param(d),{headers:{"Content-Type":"application/x-www-form-urlencoded"}}).success(function(a){e.set("authToken",{series:a.series,
token:a.token});angular.extend(c.currentUser,a.principal);e.set("loggedInUser",c.currentUser);f=!1;h&&h(a)})},changeUser:function(a){angular.extend(c.currentUser,a)},updateAuthToken:function(a){e.set("authToken",a)},logout:function(){e.remove("authToken");e.remove("loggedInUser");c.currentUser={};c.currentUser={roles:[a.userRoles.public]}},getCredentials:function(){return e.get("authToken")},getAuthHeader:function(){var a=this.getCredentials();return a?{AuthToken:a.series+":"+a.token}:{}},isLoggedIn:function(){return e.get("authToken")?
!0:!1},hasRole:function(a){var b=!1;angular.forEach(c.currentUser.roles,function(c){c===a&&(b=!0)});return b},isAuthorized:function(e,d,f){if("string"==typeof e||e instanceof String)e=a.userRoles[e];var m=b.get("$q").defer(),l=null,p=null;"string"==typeof e||e instanceof String?p=e:(p=e.role,l=e.url);var n=!1;angular.forEach(c.currentUser.roles,function(a){a===p&&(n=!0)});if(l&&n&&!f)return e=b.get("$http"),void 0===d&&(d=b.get("$routeParams")),f=l.match(/:[^\/]*/g),angular.forEach(f,function(a){l=
l.replace(a,d[a.substring(1)])}),e.get(l,{cache:!0}).success(function(a){return a.response?m.resolve(a.response&&n):m.reject(a.response&&n)}),m.promise;n?m.resolve(n):m.reject(n);return m.promise},protectedResourcesList:this.protectedResourcesList}}]}).provider("stAuthInterceptor",function(){var a=this;this.loginUrl="/login";this.setLoginUrl=function(a){this.loginUrl=a};this.accessDeniedUrl="/accessDenied";this.setAccessDeniedUrl=function(a){this.accessDeniedUrl=a};this.$get=["Auth","$q","$location",
"$log","CommonFunctions",function(b,d,e,c,f){function g(a,e){var c=null;angular.forEach(b.protectedResourcesList,function(b){a.match(b.url)&&e===b.method&&(c=b)});return c}function h(a){(a=a("AuthToken"))&&-1!=a.indexOf(":")&&(a=a.split(":"),b.updateAuthToken({series:a[0],token:a[1]}))}return{request:function(a){var c=g(a.url,a.method);if(c){var e=b.getCredentials();if(e)c.access&&d.when(b.isAuthorized(c.access,null,!0)).then(null,function(){return d.reject({config:a,status:403})}),angular.extend(a.headers,
{AuthToken:e.series+":"+e.token});else return d.reject({config:a,status:401})}return a||d.when(a)},responseError:function(c){c.headers&&h(c.headers);switch(c.status){case 401:return c.config.headers.AuthToken?(f.pushAlert("danger","Twoja sesja wygas\u0142a prosz\u0119 zaloguj si\u0119 jeszcze raz"),e.path(a.loginUrl)):c.config.data.match("login")?f.pushAlert("danger","B\u0142\u0119dny login lub has\u0142o"):(f.pushAlertByType("login"),e.path(a.loginUrl)),d.reject(c);case 403:return f.pushAlertByType("accessDenied"),
d.reject(c);case 400:return f.pushAlertByType("badRequest"),d.reject(c);case 441:return f.pushAlert("danger","Kto\u015b prawdopodobnie w\u0142ama\u0142 si\u0119 na Twoje konto. Zaloguj si\u0119 ponownie i zmie\u0144 has\u0142o jak najszybciej!"),b.setDeleteTokens(),e.path(a.loginUrl),d.reject(c);case 404:return f.pushAlert("danger","Strona kt\u00f3rej szukasz nie istnieje."),d.reject(c);default:return d.reject(c)}},response:function(a){h(a.headers);return a||d.when(a)}}}]}).directive("stAccessShow",
["$animator","Auth","$rootScope","$q",function(a,b,d,e){return{restrict:"A",link:function(c,d,g){function h(){if(g.stAccessShow.match("hasRole")){var a=c.$eval(g.stAccessShow);k[a?"show":"hide"](d)}else a=c.$eval(g.stAccessShow),e.when(a).then(function(a){k[a?"show":"hide"](d)},function(a){k.hide(d)})}var k=a(c,g);c.hasRole=b.hasRole;c.isAuthorized=b.isAuthorized;k.hide(d);c.$eval(g.stRegisterWatch);c.$watchCollection("currentUser",function(){h()})}}}]);app.service("AdService",["$http","$route","$location","CommonFunctions",function(a,b,d,e){var c=this,f={search:!0,filters:{tagList:!0,brandList:!0,place:!0,year:!0,rank:!0,votes:!0,order:!0,orderBy:!0}};this.postAd=function(b,c,e){a.post("/ad",b).success(c)};this.getAdById=function(b,c,e){a.get("/ad/"+b).success(c)};this.getAds=function(b,c,e){a.get("/ad",{params:b}).success(c)};this.rate=function(b,c,d,f){a.post("/ad/"+b+"/rate",$.param({rank:c}),e.getPostHeader()).success(d)};this.getSearchOptions=
function(){var a={};$.extend(!0,a,f,b.current.$$route.adSearchOptions);return a};this.getAdsByUrl=function(b,c){var f=e.getTranslatedUrl(),m=d.search()||{};a.get(f,{params:m}).success(b)};this.getPossibleTags=function(b,c){a.get("/tag").success(b)};this.getPossibleBrands=function(b,c){a.get("/brand/sm").success(b)};this.fetchPossibleBrands=function(a){c.getPossibleBrands(function(b){a.resolve(b)},function(b){a.reject(b)})};this.fetchPossibleTags=function(a){c.getPossibleTags(function(b){a.resolve(b)},
function(b){a.reject(b)})};this.fetchWistiaProjectId=function(b,c,e){a.get("/brand/"+b+"/wistiaproject").success(c)};this.postBrandAd=function(b,c,e,d){a.post("/brand/"+b+"/ad",c).success(e)};this.changeState=function(b,c,d,f){a.post("/ad/"+b+"/state",$.param(c),e.getPostHeader()).success(d)};this.reportAbuse=function(b,c,d,f){a.post("/ad/"+b+"/report",$.param({message:c}),e.getPostHeader()).success(d)}}]);app.service("CompanyService",["$http","$location","CommonFunctions",function(a,b,d){this.register=function(b,c,d){a.post("/company",b).success(c).error(d)};this.activateCompany=function(b,c,d){a.get("/company/"+b+"/activate").success(c)};this.fetchUserCompanies=function(b,c,d){a.get("/user/"+b+"/company").success(c)};this.fetchCompanyBrands=function(b,c,d){a.get("/company/"+b+"/brand").success(c)};this.fetchBrands=function(b,c){a.get("/brand").success(b)};this.fetchBrand=function(b,c,d){a.get("/brand/"+
b).success(c)};this.registerBrand=function(b,c,d,g){a.post("/company/"+b+"/brand",c).success(d)};this.updateBrand=function(b,c,d,g){a.post("/brand/"+b,c).success(d)};this.getBrandStats=function(b,c,f,g){a.post("/brand/"+b+"/stats",$.param(c),d.getPostHeader()).success(f)}}]);app.service("ContestService",["$http","$location","CommonFunctions",function(a,b,d){this.getContestsByUrl=function(e,c){var f=d.getTranslatedUrl(),g=b.search()||{};a.get(f,{params:g}).success(e)};this.fetchContest=function(b,c,d){a.get("/contest/"+b).success(c)};this.registerContest=function(b,c,d,g){a.post("/brand/"+b+"/contest",c).success(d)};this.updateContest=function(b,c,d,g){a.post("/contest/"+b,c).success(d)};this.registerAnswer=function(b,c,f,g){a.post("/contest/"+b+"/answer",$.param(c),d.getPostHeader()).success(f).error(g)};
this.getAnswers=function(b,c,d){a.get("/contest/"+b+"/answer").success(c)};this.updateWinner=function(b,c,f,g,h){a.post("/contest/"+b+"/answer/"+c+"/state",$.param({winner:f}),d.getPostHeader()).success(g)}}]);app.service("UserService",["$http","$route","$location","CommonFunctions",function(a,b,d,e){this.fetchUserProfile=function(b,d,e){a.get("/user/"+b+"/profile").success(d)};this.activateUser=function(b,d,e){a.get("/user/activate/"+b).success(d)};this.recoverPassword=function(b,d,g){a.post("/user/password/recover",$.param({mail:b}),e.getPostHeader()).success(d)}}]);
/** 
@ignore
**/