var app=angular.module("spotnikApp","ui.bootstrap st-auth-module blueimp.fileupload st-common-module seo FacebookPluginDirectives".split(" "));
app.factory("BaseUrlInterceptor",function(){return{request:function(a){"app"==a.url.substring(0,3)||"template"==a.url.substring(0,8)||a.url.match(".html")||(a.url="/api"+a.url);return a}}}).factory("CursorChangeInterceptor",["$q",function(a){return{request:function(a){a.url.match("api")&&!a.url.match("auth")&&$("body").css("cursor","progress");return a},response:function(a){a.config.url.match("api")&&!a.config.url.match("auth")&&$("body").css("cursor","default");return a},responseError:function(c){c.config.url.match("api")&&
!c.config.url.match("auth")&&$("body").css("cursor","default");return a.reject(c)}}}]).config(["$routeProvider","$httpProvider","stAuthInterceptorProvider","AuthProvider","CommonFunctionsProvider","$locationProvider","MetatagsCreatorProvider",function(a,c,e,d,b,f,g){function h(a,c,b,d){var g=a.defer();a=function(a){d?g.resolve(a[d]):g.resolve(a)};b?c(b,a):c(a);return g.promise}f.html5Mode(!1).hashPrefix("!");f={admin:"admin",public:"public",user:"user",company:"company",contest:"contest",thisBrand:{role:"company",
url:"/auth/brand/:brandId"},thisContest:{role:"company",url:"/auth/contest/:contestId"}};var k={possibleTags:["$q","AdService",function(a,c){var b=a.defer(),d=c.getSearchOptions();d.search&&d.filters.tagList?c.fetchPossibleTags(b):b.resolve([]);return b.promise}],possibleBrands:["$q","AdService",function(a,c){var b=a.defer(),d=c.getSearchOptions();d.search&&d.filters.brandList?c.fetchPossibleBrands(b):b.resolve([]);return b.promise}],adBrowserWrapper:["$q","AdService",function(a,b){return h(a,b.getAdsByUrl)}]};
a.when("/",{redirectTo:"/glowna"}).when("/glowna",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k}).when("/reklamy/dodaj",{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",access:"user",resolve:{possibleBrands:["$q","AdService",function(a,b){return h(a,b.getPossibleBrands)}],possibleTags:["$q","AdService",function(a,b){return h(a,b.getPossibleTags)}]}}).when("/reklamy/:adId",{controller:"AdSearchCtrl",
templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k,writeOGMetaTags:!0}).when("/poczekalnia",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k}).when("/szukaj",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/ad.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k}).when("/przegladaj",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,
adSearchOptions:{},resolve:k}).when("/losuj/",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,adSearchOptions:{search:!1},resolve:k}).when("/uzytkownik/:userId/reklamy",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,resolve:k}).when("/konkursy",{controller:"ContestListCtrl",templateUrl:"app/partials/contest/contest-list.html",reloadOnSearch:!1,resolve:{contestsBrowserWrapper:["$q","ContestService","$route",function(a,b,
c){return h(a,b.getContestsByUrl)}]}}).when("/konkursy/:contestId/reklamy",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",reloadOnSearch:!1,adSearchOptions:{filters:{brands:!1}},resolve:k}).when("/konkursy/:contestId/odpowiedzi",{controller:"ContestAnswerListCtrl",templateUrl:"app/partials/contest/contest-answer.html",resolve:{answerBrowserWrapper:["$q","ContestService","$route",function(a,b,c){return h(a,b.getAnswers,c.current.params.contestId)}]}}).when("/konkursy/:contestId/reklamy/dodaj",
{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",resolve:{possibleBrands:["$q","AdService","$route","Auth","ContestService",function(a,b,c,d,g){var k=a.defer();g.fetchContest(c.current.params.contestId,function(a){d.hasRole("company")?b.fetchWistiaProjectId(a.brand.id,function(b){ad.brand.wistiaProjectId=b.response;k.resolve(a)}):k.resolve(a)});return k.promise}],possibleTags:["$q","AdService",function(a,b){return h(a,b.getPossibleTags)}]}}).when("/konkursy/:contestId/odpowiedzi/dodaj",
{controller:"ContestAnswerRegistrationCtrl",templateUrl:"app/partials/contest/contest-answer-registration.html",access:f.user}).when("/marki/:brandId/reklamy",{controller:"AdSearchCtrl",templateUrl:"app/partials/ad/search.html",adSearchOptions:{filters:{brands:!1}},resolve:k}).when("/marki/:brandId/reklamy/dodaj",{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",access:"thisBrand",resolve:{possibleBrands:["$q","AdService","$route",function(a,b,c){var d=a.defer();
b.fetchWistiaProjectId(c.current.params.brandId,function(a){var b={brand:{}};b.brand.wistiaProjectId=a.response;d.resolve(b)});return d.promise}],possibleTags:["$q","AdService",function(a,b){return h(a,b.getPossibleTags)}]}}).when("/reklamy/:parentId/odpowiedz",{controller:"AdRegistrationCtrl",templateUrl:"app/partials/ad/ad-registration.html",access:"user",resolve:{possibleBrands:["$q","AdService","$route","Auth",function(a,b,c,d){var g=a.defer();b.getAdsByUrl(function(a){d.hasRole("company")?b.fetchWistiaProjectId(a.brand.id,
function(b){a.brand.wistiaProjectId=b.response;g.resolve(a)}):g.resolve(a)});return g.promise}],possibleTags:["$q","AdService",function(a,b){return h(a,b.getPossibleTags)}]}}).when("/marki/:brandId/konkursy",{controller:"ContestListCtrl",templateUrl:"app/partials/contest/contest-list.html",reloadOnSearch:!1,resolve:{contestsBrowserWrapper:["$q","ContestService","$route",function(a,b,c){return h(a,b.getContestsByUrl)}]}}).when("/marki/:brandId/statystyki",{controller:"BrandStatsCtrl",templateUrl:"app/partials/company/brand-stats.html",
resolve:{stats:["$q","CompanyService","$route",function(a,b,c){dateModel={};dateModel.endDate=new Date;dateModel.startDate=new Date(dateModel.endDate.getFullYear(),dateModel.endDate.getMonth(),1);var d=a.defer();b.getBrandStats(c.current.params.brandId,dateModel,function(a){d.resolve(a)});return d.promise}]}}).when("/konkursy/:contestId",{controller:"ContestCtrl",templateUrl:"app/partials/contest/contest.html",resolve:{contest:["$q","ContestService","$route",function(a,b,c){return h(a,b.fetchContest,
c.current.params.contestId)}]}}).when("/konkursy/:contestId/edytuj",{controller:"ContestRegistrationCtrl",templateUrl:"app/partials/contest/contest-registration.html",resolve:{contest:["$q","ContestService","$route",function(a,b,c){return h(a,b.fetchContest,c.current.params.contestId)}]},access:f.thisContest}).when("/uzytkownik/zaloguj",{controller:"UserLoginCtrl",templateUrl:"app/partials/user/user-login.html"}).when("/marki/:brandId/konkursy/zarejestruj",{controller:"ContestRegistrationCtrl",templateUrl:"app/partials/contest/contest-registration.html",
access:"company",resolve:{contest:function(){return null}}}).when("/uzytkownik/zaloguj",{controller:"UserLoginCtrl",templateUrl:"app/partials/user/user-login.html"}).when("/uzytkownik/zarejestruj",{controller:"UserRegistrationCtrl",templateUrl:"app/partials/user/user-registration.html"}).when("/uzytkownik/haslo/przypomnij",{controller:"PassRecoverCtrl",templateUrl:"app/partials/user/password-recovery.html"}).when("/uzytkownik/haslo/zmien",{controller:"PassChangeCtrl",templateUrl:"app/partials/user/user-change-password.html"}).when("/uzytkownik/:userId/profil",
{controller:"UserProfileCtrl",templateUrl:"app/partials/user/profile.html",access:"user",resolve:{profileData:["$q","$http","$rootScope","UserService",function(a,b,c,d){return h(a,d.fetchUserProfile,c.currentUser.id,"response")}]}}).when("/uzytkownik/aktywuj/:token",{resolve:{activate:["$q","$http","$route","UserService","$location","CommonFunctions",function(a,b,c,d,g,k){var e=a.defer();d.activateUser(c.current.params.token,function(a){a.response?k.pushAlert("success","U\u017cytkownik zosta\u0142 zaaktywowany pomy\u015blnie. Mo\u017cesz si\u0119 teraz zalogowa\u0107"):
k.pushAlert("danger","Ten kod aktywacyjny zosta\u0142 u\u017cyty ju\u017c wcze\u015bniej");g.path("/uzytkownik/zaloguj");e.resolve()});return e.promise}]}}).when("/partnerzy/:companyId/aktywuj",{controller:"CompanyActivateCtrl",templateUrl:"app/partials/confirm-page.html",access:f.admin}).when("/partnerzy/zarejestruj",{controller:"CompanyRegistrationCtrl",templateUrl:"app/partials/company/company-registration.html",access:"user"}).when("/partnerzy/:companyId",{controller:"BrandListCtrl",templateUrl:"app/partials/company/company.html",
access:"company",resolve:{brands:["$q","CompanyService","$rootScope",function(a,b,c){if(c.currentUser.companyId)return h(a,b.fetchCompanyBrands,c.currentUser.companyId)}]}}).when("/marki",{controller:"BrandListCtrl",templateUrl:"app/partials/company/brand-list.html",resolve:{brands:["$q","CompanyService","$rootScope",function(a,b,c){return h(a,b.fetchBrands)}]}}).when("/partnerzy/:companyId/marki/zarejestruj",{controller:"BrandRegistrationCtrl",templateUrl:"app/partials/company/brand-registration.html",
access:"company",resolve:{brand:function(){return null}}}).when("/marki/:brandId",{controller:"BrandCtrl",templateUrl:"app/partials/company/brand.html",resolve:{brand:["$q","CompanyService","$route",function(a,b,c){return h(a,b.fetchBrand,c.current.params.brandId)}]}}).when("/marki/:brandId/edytuj",{controller:"BrandRegistrationCtrl",templateUrl:"app/partials/company/brand-registration.html",access:"thisBrand",resolve:{brand:["$q","CompanyService","$route",function(a,b,c){return h(a,b.fetchBrand,
c.current.params.brandId)}]}}).otherwise({redirectTo:"/"});d.setProtectedResourcesList([{url:"/ad",method:"POST",access:"user"},{url:"/ad/*/rate",method:"POST",access:"user"},{url:"/ad/*/state",method:"POST",access:"admin"},{url:"/user/*/password",method:"POST",access:"user"},{url:"/user/*/profile",method:"GET",access:"user"},{url:"/user/*/",method:"POST",access:"user"},{url:"/company",method:"POST",access:"user"},{url:"/company/*/brand",method:"GET",access:"company"},{url:"/company/*/activate",method:"GET",
access:"admin"},{url:"/company/*/brand",method:"POST",access:"company"},{url:"/brand/*",method:"POST",access:"company"},{url:"/brand/*/contest",method:"POST",access:"company"},{url:"contest/*",method:"POST",access:"company"},{url:"/contest/*/answer",method:"POST",access:"user"},{url:"/contest/*/answer",method:"GET",access:"contest"},{url:"/auth/*",method:"GET",access:"user"},{url:"/user/login/status",method:"GET",access:"user"}]);d.setUserRoles(f);e.setLoginUrl("/uzytkownik/zaloguj");c.interceptors.push("BaseUrlInterceptor");
c.interceptors.push("CursorChangeInterceptor");c.interceptors.push("stAuthInterceptor");b.setWordMappings({uzytkownik:"user",konkursy:"contest",reklamy:"ad",losuj:"ad/rand",poczekalnia:"ad?place\x3d1",szukaj:"ad",glowna:"ad?place\x3d0",przegladaj:"ad",marki:"brand",odpowiedz:""});g.setDefaultMetatags({url:"http://www.spotnik.pl/#!/glowna",description:"Spotnik.pl - reklamy nie musz\u0105 by\u0107 nudne!",type:"website",image:"http://www.spotnik.pl/resources/img/logo.png",site_name:"Spotnik.pl"})}]).run(["$rootScope",
"$location","Auth","CommonFunctions","$q","MetatagsCreator",function(a,c,e,d,b,f){function g(a){if(!a)return e.isLoggedIn()?d.pushAlertByType("accessDenied"):(d.pushAlertByType("login"),c.path("/uzytkownik/zaloguj")),b.reject()}a.$on("$routeChangeStart",function(a,c,d){if(c.$$route&&c.$$route.access){a=e.isAuthorized(c.$$route.access,c.params);var f=b.when(a);f.then(g,g);c.resolve=c.resolve||{};angular.extend(c.resolve,{__authentication__:function(){return f}})}})}]);app.controller("AdSearchCtrl",["$scope","filterFilter","$location","CommonFunctions","AdService","$http","possibleTags","possibleBrands","adBrowserWrapper",function(a,c,e,d,b,f,g,h,k){function m(a,b){var c=""+b,d=$.inArray(c,a);0<=d?a.splice(d,1):a.push(c)}function l(){b.getAdsByUrl(function(b){b.ads?(a.model.ads=b.ads,a.total=b.total):a.model.ads=[b]})}function p(){a.searchOptions.filters.rank&&a.$watchCollection("filters.rankFrom + filters.rankTo",function(){a.text.rank=n(a.filters.rankFrom,a.filters.rankTo)},
!0);a.searchOptions.filters.year&&a.$watchCollection("filters.yearFrom + filters.yearTo",function(){a.text.year=n(a.filters.yearFrom,a.filters.yearTo)},!0);a.searchOptions.filters.votes&&a.$watchCollection("filters.votesFrom + filters.votesTo",function(){a.text.votes=n(a.filters.votesFrom,a.filters.votesTo)},!0);a.searchOptions.filters.place&&a.$watch("filters.place",function(b){a.text.place="";angular.forEach(a.possiblePlaces,function(c){""!==b&&b==c.value&&(a.text.place=c.label)})},!0)}function n(a,
b){if(void 0===a||null==a||0==a.length)a="";if(void 0===b||null==b||0==b.length)b="";return""==a&&""!=b?"poni\u017cej "+b:""!=a&&""==b?"powy\u017cej "+a:""==a&&""==b?"":a+" - "+b}a.search=function(){var b=a.filters;$.each(b,function(a,c){void 0!==c&&null!=c&&0!=c.length||delete b[a]});e.search(b)};a.changeOrder=function(b){a.filters.orderBy=b;a.filters.order="asc"==a.filters.order?"desc":"asc"};a.isInBrandList=function(b){return 0<=$.inArray(""+b.id,a.helper.brandArr)?!0:!1};a.toogleBrand=function(b){m(a.helper.brandArr,
b)};a.isInTagList=function(b){return 0<=$.inArray(""+b.id,a.helper.tagArr)?!0:!1};a.toogleTag=function(b){m(a.helper.tagArr,b)};a.$on("$routeUpdate",function(b){a.filters=e.search();l()});a.selectPage=function(b){a.filters.page=b;a.search()};(function(){a.filters=e.search();a.helper={};a.helper.brandArr=[];a.helper.tagArr=[];a.text={};a.possibleTags=g||[];a.possibleBrands=h||[];a.possiblePlaces=[{label:"Poczekalnia",value:1},{label:"G\u0142\u00f3wna",value:0}];a.model={};a.searchOptions=b.getSearchOptions();
a.$watch("filters.brandList",function(b){a.helper.brandArr=b?b.split(","):[]});a.$watchCollection("helper.brandArr",function(b){b&&(a.filters.brandList=b.join(","))});a.$watch("filters.tagList",function(b){a.helper.tagArr=b?b.split(","):[]});a.$watchCollection("helper.tagArr",function(b){b&&(a.filters.tagList=b.join(","))});p();void 0!==k.total?(a.model.ads=k.ads,a.total=k.total):(a.model.ads=[k],a.singleAd=k)})()}]);
app.controller("RatingCtrl",["$scope","AdService","$timeout",function(a,c,e){(function(){a.max=5;a.isReadonly=!1;a.tooltip={};a.rate=Math.floor(a.ad.rank);a.labelValue=Math.floor(a.ad.rank);a.hoveringOver=function(c){a.overStar=c;a.labelValue=c};a.onLeave=function(){a.labelValue=Math.floor(a.ad.rank);a.overStar=null;a.rate=Math.floor(a.ad.rank)};a.$watch("rate",function(d){a.overStar&&c.rate(a.$parent.ad.id,d,function(){a.tooltip.ranked=!0})});a.$watch("ad.rank",function(c){a.rate=Math.floor(a.ad.rank);
a.labelValue=Math.floor(a.ad.rank)});a.ratingStates=[{stateOn:"icon-star icon-large",stateOff:"icon-star-empty icon-large"}]})()}]);
app.controller("AdRegistrationCtrl",["$scope","possibleBrands","possibleTags","$modal","filterFilter","ErrorFactory","$location","AdService","Auth","$routeParams",function(a,c,e,d,b,f,g,h,k,m){var l=a.$new(),p=null,n=a.$new(),q=null;(function(){a.regModel={};a.regModel.tags=[];a.selectedTags="";a.possibleTags=e||[];a.yearMax=(new Date).getFullYear();a.errorMessages=f.getErrorMessages({pattern:{url:"Tylko prawid\u0142owe linki youtube"}});a.companyUser=k.hasRole("company");m.contestId&&(a.regModel.contestId=
m.contestId,a.regModel.brandId=c.brand.id);m.parentId&&(a.regModel.parentId=m.parentId,a.regModel.brandId=c.brand.id);m.brandId&&(a.regModel.brandId=m.brandId);if(a.companyUser){var b=c.brand.wistiaProjectId;m.parentId||m.contestId?a.$watch("regModel.videoId",function(b){a.regModel.videoId&&h.postAd(a.regModel,function(a){g.path("/reklamy/"+a.response)})}):a.$watch("regModel.videoId",function(b){a.regModel.videoId&&h.postBrandAd(a.regModel.brandId,a.regModel,function(b){g.path("/marki/"+a.regModel.brandId+
"/reklamy")})});new wistia.UploadWidget({divId:"wistia-upload-widget",publicProjectId:b,buttonText:"Dodaj reklam\u0119",callbacks:{uploadSuccess:function(b){a.regModel.videoId=b.hashed_id;a.regModel.thumbnail=b.thumbnail.url;a.regModel.duration=Math.floor(b.duration);a.$apply()},fileQueued:function(a){a=a.name.split(".").pop().toLowerCase();-1==$.inArray(a,"mov mpg avi flv f4v mp4 m4v asf wmv vob mod 3gp mkv divx xvid".split(" "))?(this.cancelUpload(),this.reset(),$(".upload-status").addClass("hidden"),
$("#upload-file-error").html("Tylko pliki z ro\u017cszerzeniem mov, mpg, avi, flv, f4v, mp4, m4v, asf, wmv, vob, mod, 3gp, mkv, divx, xvid"),$("#upload-file-error").removeClass("hidden")):($(".upload-status").removeClass("hidden"),$("#upload-file-error").addClass("hidden"))}}})}else a.possibleBrands=c||[],l.items=c,l.title="Wybierz mark\u0119",l.type=0,a.openBrandsModal=function(){p=d.open({templateUrl:"tagsBrandsPickerModal.html",scope:l})},l.click=function(b){a.selectedBrandName=b.name;a.regModel.brandId=
b.id;p.close()};n.items=e;n.title="Wybierz kategorie";n.type=1;a.openTagsModal=function(){q=d.open({templateUrl:"tagsBrandsPickerModal.html",scope:n})};n.ok=function(){q.close()};a.register=function(){h.postAd(a.regModel,function(a){g.path("reklamy/"+a.response)})};a.click=function(b,c){b.selected=!b.selected;if(b.selected)a.regModel.tags.push(b.id);else{var d=a.regModel.tags.indexOf(b.id);a.regModel.tags.splice(d,1)}a.selectedTags=a.regModel.tags.join();c&&c.stopPropagation()}})()}]);
app.controller("TopAdsCtrl",["$scope","AdService",function(a,c){(function(){a.model={};c.getAds({orderBy:"rank",order:"desc",page:"1"},function(c){a.model.topAds=c.ads});a.roundRank=function(a){return Math.floor(a)}})()}]);
app.controller("AdAdminPanelCtrl",["$scope","AdService",function(a,c){(function(){a.model={};a.changePlace=function(a,d,b){c.changeState(a.id,{place:d},function(c){a.place=b})};a.changeApproved=function(a){c.changeState(a.id,{approved:!a.approved},function(c){a.approved=!a.approved})};a.changeAgeProtected=function(a){c.changeState(a.id,{ageProtected:!a.ageProtected},function(c){a.ageProtected=!a.ageProtected})}})()}]);
app.controller("AdCtrl",["$scope","AdService","$rootScope","$route","$location","$timeout",function(a,c,e,d,b,f){(function(){a.model={};a.tooltip={};a.reportAbuse=function(){c.reportAbuse(a.ad.id,a.model.abuseMessage,function(){a.tooltip.informSent=!0;a.model.abuseMessage="";f(function(){a.bottomVideoPanelView=""},1E3)})};d.current.$$route.writeOGMetaTags&&(a.metatags.title=a.ad.title,a.metatags.description=a.ad.description.substring(0,160),a.metatags.image="youtube"==a.ad.videoData.provider.name?
a.ad.videoData.provider.thumbnailUrl+"/"+a.ad.videoData.videoId+"/0.jpg":a.ad.thumbnail.replace(/image_crop_resized=.*&/,""),a.metatags.url="http://www.spotnik.pl/#!/reklamy/"+a.ad.id)})()}]);app.controller("SearchInputCtrl",["$scope","$location",function(a,c){(function(){a.model={};a.search=function(){c.path("/szukaj/");c.search({});c.search(a.model)}})()}]);app.controller("CompanyRegistrationCtrl",["CompanyService","$location","$scope","$rootScope","ErrorFactory","CommonFunctions",function(a,c,e,d,b,f){(function(){e.regModel={};e.regModel.address={};e.errorMessages=b.getErrorMessages({});e.register=function(){a.register(e.regModel,function(a){f.pushAlert("success","Dzi\u0119kujemy za ch\u0119\u0107 wsp\u00f3\u0142pracy z nami. W ci\u0105gu 24h otrzymasz od nas email z dalszymi instrukcjami.");c.path("/")},function(a,b){443==b&&f.pushAlert("danger","Ju\u017c wcze\u015bniej wyrazi\u0142e\u015b/\u0142a\u015b ch\u0119\u0107 wsp\u00f3\u0142pracy z nami. Je\u015bli nie dosta\u0142e\u015b/\u0142a\u015b od nas wiadomo\u015bci w ci\u0105gu 24h od rejestracji skontaktuj si\u0119 z nami.")})}})()}]);
app.controller("CompanyActivateCtrl",["$routeParams","CompanyService","$location","CommonFunctions","$scope",function(a,c,e,d,b){(function(){b.message="Czy chcesz aktywowa\u0107 firm\u0119.";b.cancel=function(){e.path("/")};b.ok=function(){c.activateCompany(a.companyId,function(a){a.response?d.pushAlert("success","Firma zosta\u0142a zaaktywowana pomy\u015blnie."):d.pushAlert("success","Firma ju\u017c wcze\u015bniej zosta\u0142a zaaktywowana.");e.path("/")})}})()}]);
app.controller("BrandListCtrl",["brands","$scope",function(a,c){c.brands=a}]);app.controller("BrandStatsCtrl",["stats","$scope","CompanyService","$routeParams",function(a,c,e,d){(function(){c.wistiaStats=a;c.dateModel={};c.getStats=function(){e.getBrandStats(d.brandId,c.dateModel,function(a){c.wistiaStats=a})}})()}]);app.controller("BrandCtrl",["brand","$scope",function(a,c){c.brand=a}]);
app.controller("BrandRegistrationCtrl",["$scope","ErrorFactory","$location","$routeParams","CompanyService","brand","Auth",function(a,c,e,d,b,f,g){(function(){a.regModel={};a.errorMessages=c.getErrorMessages({});f?(a.regModel.name=f.name,a.regModel.description=f.description,a.locationEdit=!0,a.brand=f,a.submitText="Zaktualizuj",a.options={url:"/api/brand/"+d.brandId+"/upload/image",type:"POST",dataType:"json",headers:{},autoUpload:!0},$.extend(a.options.headers,g.getAuthHeader()),$("#fileupload").bind("fileuploaddone",
function(b,c){a.brand.smallLogoUrl=c.result.small;a.brand.logoUrl=c.result.big}),a.register=function(){b.updateBrand(d.brandId,a.regModel,function(a){e.path("/marki/"+d.brandId)})}):(a.register=function(){b.registerBrand(d.companyId,a.regModel,function(a){e.path("/marki/"+a.response+"/edytuj")})},a.submitText="Dodaj mark\u0119")})()}]);app.controller("ContestListCtrl",["contestsBrowserWrapper","$scope","$location","ContestService","$routeParams",function(a,c,e,d,b){function f(){d.getContestsByUrl(function(a){c.total=a.total;c.contests=a.contests})}(function(){c.filters=e.search();c.contests=a.contests;c.total=a.total;c.selectPage=function(a){c.filters.page=a;e.search(c.filters)};c.$on("$routeUpdate",function(a){c.filters=e.search();f()})})()}]);
app.controller("ContestAnswerListCtrl",["answerBrowserWrapper","$scope","$routeParams","ContestService",function(a,c,e,d){(function(){c.contestAnswers=a.contestAnswers;c.total=a.total;c.currentPage=1;c.selectPage=function(a){c.filters.page=a;c.search()};c.pressWinner=function(a){d.updateWinner(e.contestId,a.id,!a.winner,function(c){a.winner=!a.winner})}})()}]);
app.controller("ContestAnswerRegistrationCtrl",["ContestService","$scope","$routeParams","ErrorFactory","$location","CommonFunctions",function(a,c,e,d,b,f){(function(){c.regModel={};c.errorMessages=d.getErrorMessages({});c.submit=function(){a.registerAnswer(e.contestId,c.regModel,function(a){f.pushAlert("success","Twoja odpowied\u017a zosta\u0142a zarejestrowana");b.path("/konkursy/"+e.contestId)},function(a,b){442==b?f.pushAlert("danger","Konkurs ju\u017c si\u0119 zako\u0144czy\u0142"):443==b&&f.pushAlert("danger",
"Ju\u017c wcze\u015bniej doda\u0142e\u015b/a\u015b odpowied\u017a")})}})()}]);app.controller("ContestCtrl",["contest","$scope",function(a,c){c.contest=a}]);
app.controller("ContestRegistrationCtrl",["$scope","ErrorFactory","$location","$routeParams","ContestService","$filter","contest",function(a,c,e,d,b,f,g){function h(){var b=angular.copy(a.regModel);b.finishDate=new Date(b.finishDate.date.getFullYear(),b.finishDate.date.getMonth(),b.finishDate.date.getDate(),b.finishDate.time.getHours(),b.finishDate.time.getMinutes(),b.finishDate.time.getSeconds());b.scoresDate=new Date(b.scoresDate.date.getFullYear(),b.scoresDate.date.getMonth(),b.scoresDate.date.getDate(),
b.scoresDate.time.getHours(),b.scoresDate.time.getMinutes(),b.scoresDate.time.getSeconds());return b}(function(){a.regModel={};a.regModel.scoresDate={};a.regModel.finishDate={};a.minDate=new Date;a.errorMessages=c.getErrorMessages({dateValid:{scoresDate:"Data musi by\u0107 po\u017aniejsza",finishDate:"Data musi by\u0107 po\u017aniejsza"}});g?(a.regModel.name=g.name,a.regModel.description=g.description,a.regModel.finishDate.date=new Date(g.finishDate),a.regModel.finishDate.time=new Date(g.finishDate),
a.regModel.scoresDate.date=new Date(g.scoresDate),a.regModel.scoresDate.time=new Date(g.scoresDate),a.regModel.type=g.type,a.register=function(){var a=h();b.updateContest(d.contestId,a,function(a){e.path("/konkursy/"+d.contestId)})}):(a.regModel.finishDate.time=new Date,a.regModel.scoresDate.time=new Date,a.register=function(){var a=h();b.registerContest(d.brandId,a,function(a){e.path("/konkursy/"+a.response)})});a.minDate=new Date;a.$watchCollection("regModel.finishDate",function(b){b.date&&b.time&&
a.contestRegForm.finishDate&&(new Date(b.date.getFullYear(),b.date.getMonth(),b.date.getDate(),b.time.getHours(),b.time.getMinutes(),b.time.getSeconds())<=new Date?a.contestRegForm.finishDate.$setValidity("dateValid",!1):a.contestRegForm.finishDate.$setValidity("dateValid",!0))});a.$watchCollection("regModel.finishDate",function(b){b.date&&b.time&&a.contestRegForm.finishDate&&(new Date(b.date.getFullYear(),b.date.getMonth(),b.date.getDate(),b.time.getHours(),b.time.getMinutes(),b.time.getSeconds())<=
new Date?a.contestRegForm.scoresDate.$setValidity("dateValid",!1):a.contestRegForm.scoresDate.$setValidity("dateValid",!0))})})()}]);app.controller("UserLoginCtrl",["$scope","ErrorFactory","Auth","$location",function(a,c,e,d){a.loginModel={};a.login=function(){e.login(a.loginModel,function(){d.path("/")})}}]);
app.controller("UserProfileCtrl",["$scope","$location","profileData","$http","CommonFunctions","$routeParams","Auth",function(a,c,e,d,b,f,g){a.profileModel=e;a.update=function(){d.post("/user/"+a.currentUser.id+"/",a.profileModel).success(function(){b.pushAlert("success","Dane u\u017cytkownika zosta\u0142y zaktualizowane")})};a.options={url:"/api/user/"+f.userId+"/upload/image",type:"POST",dataType:"json",headers:{},autoUpload:!0};$.extend(a.options.headers,g.getAuthHeader());$("#fileupload").bind("fileuploaddone",
function(a,b){g.changeUser({imageUrl:b.result.response})})}]);
app.controller("PassRecoverCtrl",["$scope","$location","$http","CommonFunctions","ErrorFactory","UserService",function(a,c,e,d,b,f){a.recoverModel={};a.errorMessages=b.getErrorMessages({});a.recover=function(){f.recoverPassword(a.recoverModel.email,function(b){b.response?d.pushAlert("success","Wys\u0142ali\u015bmy has\u0142o na podany adres email: "+a.recoverModel.email):d.pushAlert("danger","Podany adres email: "+a.recoverModel.email+" nie istnieje w naszej bazie.");c.path("/uzytkownik/zaloguj")})}}]);
app.controller("PassChangeCtrl",["$scope","$location","$http","CommonFunctions","ErrorFactory","$rootScope",function(a,c,e,d,b,f){a.changePassModel={};a.errorMessages=b.getErrorMessages({});a.change=function(){e.post("/user/"+f.currentUser.id+"/password",a.changePassModel).success(function(b){b.response?(d.pushAlert("success","Has\u0142o zosta\u0142o zmienione"),c.path("/")):(d.pushAlert("danger","Nieprawid\u0142owe has\u0142o"),a.changePassModel.oldPassword="")})}}]);
app.controller("UserRegistrationCtrl",["$scope","ErrorFactory","$locale","$location","$http","CommonFunctions","$filter",function(a,c,e,d,b,f,g){(function(){a.regModel={};a.errorMessages=c.getErrorMessages({pattern:{username:"Tylko litery i cyfry"},unique:{username:"Taki u\u017cytkownik ju\u017c istnieje",email:"Taki adres email ju\u017c istnieje"}});a.months=e.DATETIME_FORMATS.MONTH;a.register=function(){var c=angular.copy(a.regModel);c.birthdate=("0"+a.regModel.birthdate.year).slice(-4)+"-"+("0"+
a.regModel.birthdate.month).slice(-2)+"-"+("0"+a.regModel.birthdate.day).slice(-2);b({method:"POST",url:"/user",data:c}).success(function(b){f.pushAlert("success","U\u017cytkownik zosta\u0142 zarejestrowany. Prosimy o potwierdzenie rejestracji poprzez klikni\u0119cie w link kt\u00f3ry wys\u0142ali\u015bmy na podany adres email: "+a.regModel.mail);d.path("/uzytkownik/zaloguj")})}})()}]);
app.controller("UserDropdownCtrl",["$scope","Auth","$location",function(a,c,e){a.logout=function(){c.logout();e.path("/")};a.showProfile=function(){e.path("/uzytkownik/"+a.currentUser.id+"/profil")}}]);app.directive("stSubmit",["$parse",function(a){return{restrict:"A",require:["stSubmit","?^form"],controller:["$scope",function(a){this.attempted=!1;var e=null;this.setAttempted=function(){this.attempted=!0};this.setFormController=function(a){e=a};this.needsAttention=function(a){return e?a?a.$invalid&&this.attempted:e&&e.$invalid&&(e.$dirty||this.attempted):!1}}],compile:function(c,e,d){return{pre:function(a,c,d,e){c=e[0];c.setFormController(1<e.length?e[1]:null);a.st=a.st||{};a.st[d.name]=c;a.st.busy=
[]},post:function(b,c,d,e){var k=e[0],m=1<e.length?e[1]:null,l=a(d.stSubmit);c.bind("submit",function(){k.setAttempted();b.$$phase||b.$apply();if(!m.$valid||0<b.st.busy.length)return!1;c.find(":submit").attr("disabled",!0);b.$apply(function(){l(b,{$event:event})})})}}}}}]);
app.directive("stError",function(){return{restrict:"A",require:"^form",link:function(a,c,e,d){var b=$("[name\x3d"+d.$name+"]").find("[name\x3d"+e.stError+"]"),f=e.stErrorMessagesVar?e.stErrorMessagesVar:"errorMessages";a.$watchCollection(d.$name+"."+e.stError+".$error",function(d){var h=!1;angular.forEach(d,function(d,g){if(d){var l=a[f][g],p=null;l&&(p=l[e.stError]?l[e.stError]:l.def,p.match("{{.*}}")&&(l=p.match("{{.*}}","g"),$.each(l,function(a,c){c=c.replace(RegExp("{","g"),"").replace(RegExp("}",
"g"),"");b.attr(c)&&(p=p.replace("{{"+c+"}}",b.attr(c)))})),c.removeClass("hidden"),c.text(p));h=!0}});h||c.addClass("hidden")},!0)}}});app.directive("stFieldMatch",["$parse",function(a){return{require:"ngModel",link:function(c,e,d,b){b.$setValidity("fieldMatch",!1);c.$watch(function(){return a(d.stFieldMatch)(c)===b.$modelValue},function(a){b.$setValidity("fieldMatch",a);b.$dirty=!0})}}}]);
app.directive("stDateValidation",["$parse",function(a){return{require:"ngModel",link:function(a,e,d,b){b.$setValidity("dateValid",!1);var f=/^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$/i;a.$watchCollection(d.stDateValidation,
function(a){a&&a.day&&a.month&&a.year?(a=("0"+a.day).slice(-2)+"."+("0"+a.month).slice(-2)+"."+a.year,a=f.test(a),b.$setValidity("dateValid",a)):b.$setValidity("dateValid",!1);b.$dirty=!0})}}}]);app.filter("stErrorMessagesFilter",function(){return function(a,c){var e={};angular.forEach(a,function(a,b){a==c&&(e[b]=a)});return e}});
app.directive("stActive",["$location",function(a){return{restrict:"A",link:function(c,e,d){c.$on("$routeChangeSuccess",function(b,c,d){$.each(e.children("li"),function(b,c){var d=$(c),e=d.children("a");e&&$(e).attr("href")&&($(e).attr("href").replace("#!","")===a.path()?d.addClass("active"):d.removeClass("active"))})})}}}]);
app.directive("stEnsureUnique",["Auth","$timeout",function(a,c){return{restrict:"A",require:"ngModel",link:function(e,d,b,f){var g;e.$watch(function(){return f.$modelValue},function(d){d&&(c.cancel(g),g=c(function(){e.st.busy.push(b.name);a[b.name+"Exist"](d,function(a){f.$setValidity("unique",!a);f.$dirty=!0;e.st.busy.splice(e.st.busy.indexOf(b.name),1)})},200))})}}}]);
app.directive("numbersOnly",function(){return{require:"ngModel",link:function(a,c,e,d){d.$parsers.push(function(a){if(void 0==a)return"";var c=a.replace(/[^0-9]/g,"");c!=a&&(d.$setViewValue(c),d.$render());return c})}}});
app.directive("stValidFormElem",function(){return{restrict:"A",require:"^form",replace:!0,transclude:!0,scope:!0,templateUrl:"app/partials/valid-form-elem.html",compile:function(a,c,e){return{pre:function(a,b,c,e){a.stForm=a[e.$name];a.stFormName=e.$name;a.stLabel=c.stLabel;a.stName=c.stName;a.stIcon=c.stIcon;a.stInputGroup=a.$eval(c.stInputGroup);void 0===a.stInputGroup&&(a.stInputGroup=!0)}}}}});
app.directive("ngFocus",["$parse",function(a){return function(c,e,d){var b=a(d.ngFocus);e.bind("focus",function(a){c.$apply(function(){b(c,{$event:a})})})}}]);angular.module("st-common-module",["ngCookies","angularLocalStorage"]).controller("PagingCtrl",["$scope","$location",function(a,c){a.filters.page=parseInt(a.filters.page)||1;a.$watch("filters.page",function(c){a.currentPage=parseInt(a.filters.page)||1;window.scrollTo(0,0)})}]).provider("CommonFunctions",function(){var a=this;this.wordMappings={};this.setWordMappings=function(a){this.wordMappings=a};this.$get=["$rootScope","$location","$timeout",function(c,e,d){c.alerts=[];c.closeAlert=function(a){c.alerts.splice(a,
1)};return{pushAlert:function(a,e){var g=c.alerts.push({type:a,msg:e});d(function(){c.alerts.splice(g-1)},5E3)},pushAlertByType:function(a){switch(a){case "login":this.pushAlert("danger","Musisz si\u0119 najpierw zalogowa\u0107.");break;case "accessDenied":this.pushAlert("danger","Nie masz wystarczaj\u0105cych uprawnie\u0144.");break;case "badRequest":this.pushAlert("danger","Ups, co\u015b posz\u0142o nie tak. Prosz\u0119, post\u0119puj zgodnie z podpowiedziami")}},getPostHeader:function(){return{headers:{"Content-Type":"application/x-www-form-urlencoded"}}},
translateWord:function(b){return a.wordMappings[b]},translateUrl:function(a){a=a.split("/");""==a[0]&&delete a[0];var c="/",d=this;angular.forEach(a,function(a){var b=d.translateWord(a);""==b?c+=b:(c+=b||a,c+="/")});1<c.length&&(c=c.slice(0,c.length-1));return c},getTranslatedUrl:function(){return this.translateUrl(e.path())}}}]}).factory("ErrorFactory",function(){this.errorMessages={pattern:{def:"Niew\u0142a\u015bciwe znaki"},minlength:{def:"Min {{data-ng-minlength}} znak\u00f3w"},maxlength:{def:"Max {{data-ng-maxlength}} znak\u00f3w"},
fieldMatch:{def:"Pola nie s\u0105 takie same"},email:{def:"Niepoprawny email"},dateValid:{def:"Niepoprawna data"},min:{def:"Podana liczba musi by\u0107 wi\u0119ksza od {{data-min}}"},max:{def:"Podana liczba musi by\u0107 mniejsza od {{data-max}}"}};this.getErrorMessages=function(a){return $.extend(!0,this.errorMessages,a)};return this}).directive("stTimeoutTooltip",["$animator","$timeout",function(a,c){return{restrict:"A",link:function(a,d,b){var f=b.stOn.substring(0,b.stOn.indexOf(".")),g=b.stOn.substring(b.stOn.indexOf(".")+
1);a.$watch(b.stOn,function(h){h?(d.addClass("in"),c(function(){a[f][g]=!1},b.timeout)):d.removeClass("in")})}}}]).directive("stNewWindow",function(){return{restrict:"A",link:function(a,c,e){var d=e.width?e.width:650,b=e.height?e.height:350;c.bind("click",function(a){a.preventDefault();window.open(e.href,"newwindow","width\x3d"+d+", height\x3d"+b+", left\x3d"+(screen.width/2-d/2)+", top\x3d"+(screen.height/2-b/2))})}}}).provider("MetatagsCreator",function(){var a={};this.setDefaultMetatags=function(c){a=
c};this.$get=["$rootScope",function(c){c.metatags=a}]});
(function(){var a,c,e,d,b,f;c=angular.module("FacebookPluginDirectives",[]);a=function(a){return c.directive(a,["$timeout",function(a){return{restrict:"C",compile:function(b,c,d){return{post:function(b,c,d,e){b.$watch("ad.id",function(){a(function(){return"undefined"!==typeof FB&&null!==FB?FB.XFBML.parse(c.parent()[0]):void 0},50,!1)})}}}}}])};f="fbActivity fbComments fbFacepile fbLike fbLikeBox fbLiveStream fbLoginButton fbName fbProfilePic fbRecommendations".split(" ");d=0;for(b=f.length;d<b;d++)e=
f[d],a(e)}).call(this);var test=angular.module("st-auth-module-test",["ngMockE2E"]);
test.run(function(a){a.whenGET(/app\/partials\/.*/).passThrough();a.whenPOST("/user/username").passThrough();a.whenPOST("/user/email").passThrough();a.whenGET(/\/ad.*/).passThrough();a.whenGET(/\/uzytkownik\/11\/reklamy/).respond([{title:"Bmw reklama",videoUrl:"http://youtu.be/4KVVDdnGtdM",user:{displayName:"maniekstasz",imageUrl:"resources/static/no-user.gif"},creationDate:"1382523642",description:"adsfasdfasdfasdfasdfasfsdfasdf",rank:"3.75"}]);a.whenGET("/tag").respond([{name:"napoje",selected:!1,
id:5},{name:"piwa",selected:!1,id:2},{name:"soki",selected:!1,id:1}]);a.whenGET("/brand").respond([{name:"Coca cola",selected:!1,id:2},{name:"Coca cola",selected:!1,id:2},{name:"BMW",selected:!1,id:3}]);a.whenGET("http://localhost:8080/user/username").passThrough();a.whenPOST("/user/email").passThrough();a.whenPOST("/user/login").respond({displayName:"maniekstasz",imageUrl:"asdf",roles:["user"],authToken:"asdfasfasewqrzxdxzcivqqrqwevrwqejdjfl",id:"11"});a.whenPOST("/ad/rate").respond({rank:"4.75"});
a.whenPOST("/user/password/recover").respond({});a.whenPOST("/user/password/change").respond({});a.whenPOST("/user").respond(!0)});angular.module("st-auth-module",["ngCookies","angularLocalStorage","st-common-module"]).provider("Auth",function(){var a=this;this.loginUrl="/user/login";this.userStatusUrl="/user/login/status";this.usernameExistUrl="/user/username";this.emailExistUrl="/user/email";this.userRoles={public:"public",user:"user",admin:"admin"};this.protectedResourcesList=[];this.setProtectedResourcesList=function(a){angular.forEach(a,function(a){a.url=a.url.replace(/\//g,"\\/").replace(/\*/g,"[^ ]*");a.url=RegExp("^/api"+
a.url+"$","i")});this.protectedResourcesList=a};this.setLoginUrl=function(a){this.loginUrl=a};this.setUserStatusUrl=function(a){this.userStatus=a};this.setUserRoles=function(a){this.userRoles=a};this.setUsernameExistUrl=function(a){this.usernameExistUrl=a};this.setEmailExistUrl=function(a){this.emailExistUrl=a};this.$get=["$injector","$cookieStore","storage","$rootScope",function(c,e,d,b){b.currentUser=d.get("loggedInUser")||{roles:[this.userRoles.public]};var f=!1;return{setDeleteTokens:function(){f=
!0},usernameExist:function(b,d,e){c.get("$http")({method:"GET",url:a.usernameExistUrl+"?username\x3d"+b}).success(function(a){d(a.response)}).error(e)},emailExist:function(b,d,e){c.get("$http")({method:"GET",url:a.emailExistUrl+"?email\x3d"+b}).success(function(a){d(a.response)}).error(e)},login:function(e,h,k){k=c.get("$http");f&&(e.deleteTokens=!0);k.post(a.loginUrl,$.param(e),{headers:{"Content-Type":"application/x-www-form-urlencoded"}}).success(function(a){d.set("authToken",{series:a.series,
token:a.token});angular.extend(b.currentUser,a.principal);d.set("loggedInUser",b.currentUser);f=!1;h&&h(a)})},changeUser:function(a){angular.extend(b.currentUser,a)},updateAuthToken:function(a){d.set("authToken",a)},logout:function(){d.remove("authToken");d.remove("loggedInUser");b.currentUser={};b.currentUser={roles:[a.userRoles.public]}},getCredentials:function(){return d.get("authToken")},getAuthHeader:function(){var a=this.getCredentials();return a?{AuthToken:a.series+":"+a.token}:{}},isLoggedIn:function(){return d.get("authToken")?
!0:!1},hasRole:function(a){var c=!1;angular.forEach(b.currentUser.roles,function(b){b===a&&(c=!0)});return c},isAuthorized:function(d,e,f){if("string"==typeof d||d instanceof String)d=a.userRoles[d];var m=c.get("$q").defer(),l=null,p=null;"string"==typeof d||d instanceof String?p=d:(p=d.role,l=d.url);var n=!1;angular.forEach(b.currentUser.roles,function(a){a===p&&(n=!0)});if(l&&n&&!f)return d=c.get("$http"),void 0===e&&(e=c.get("$routeParams")),f=l.match(/:[^\/]*/g),angular.forEach(f,function(a){l=
l.replace(a,e[a.substring(1)])}),d.get(l,{cache:!0}).success(function(a){return a.response?m.resolve(a.response&&n):m.reject(a.response&&n)}),m.promise;n?m.resolve(n):m.reject(n);return m.promise},protectedResourcesList:this.protectedResourcesList}}]}).provider("stAuthInterceptor",function(){var a=this;this.loginUrl="/login";this.setLoginUrl=function(a){this.loginUrl=a};this.accessDeniedUrl="/accessDenied";this.setAccessDeniedUrl=function(a){this.accessDeniedUrl=a};this.$get=["Auth","$q","$location",
"$log","CommonFunctions",function(c,e,d,b,f){function g(a,b){var d=null;angular.forEach(c.protectedResourcesList,function(c){a.match(c.url)&&b===c.method&&(d=c)});return d}function h(a){(a=a("AuthToken"))&&-1!=a.indexOf(":")&&(a=a.split(":"),c.updateAuthToken({series:a[0],token:a[1]}))}return{request:function(a){var b=g(a.url,a.method);if(b){var d=c.getCredentials();if(d)b.access&&e.when(c.isAuthorized(b.access,null,!0)).then(null,function(){return e.reject({config:a,status:403})}),angular.extend(a.headers,
{AuthToken:d.series+":"+d.token});else return e.reject({config:a,status:401})}return a||e.when(a)},responseError:function(b){b.headers&&h(b.headers);switch(b.status){case 401:return b.config.headers.AuthToken?(f.pushAlert("danger","Twoja sesja wygas\u0142a prosz\u0119 zaloguj si\u0119 jeszcze raz"),d.path(a.loginUrl)):b.config.data.match("login")?f.pushAlert("danger","B\u0142\u0119dny login lub has\u0142o"):(f.pushAlertByType("login"),d.path(a.loginUrl)),e.reject(b);case 403:return f.pushAlertByType("accessDenied"),
e.reject(b);case 400:return f.pushAlertByType("badRequest"),e.reject(b);case 441:return f.pushAlert("danger","Kto\u015b prawdopodobnie w\u0142ama\u0142 si\u0119 na Twoje konto. Zaloguj si\u0119 ponownie i zmie\u0144 has\u0142o jak najszybciej!"),c.setDeleteTokens(),d.path(a.loginUrl),e.reject(b);case 404:return f.pushAlert("danger","Strona kt\u00f3rej szukasz nie istnieje."),e.reject(b);default:return e.reject(b)}},response:function(a){h(a.headers);return a||e.when(a)}}}]}).directive("stAccessShow",
["$animator","Auth","$rootScope","$q",function(a,c,e,d){return{restrict:"A",link:function(b,e,g){function h(){if(g.stAccessShow.match("hasRole")){var a=b.$eval(g.stAccessShow);k[a?"show":"hide"](e)}else a=b.$eval(g.stAccessShow),d.when(a).then(function(a){k[a?"show":"hide"](e)},function(a){k.hide(e)})}var k=a(b,g);b.hasRole=c.hasRole;b.isAuthorized=c.isAuthorized;k.hide(e);b.$eval(g.stRegisterWatch);b.$watchCollection("currentUser",function(){h()})}}}]);app.service("AdService",["$http","$route","$location","CommonFunctions",function(a,c,e,d){var b=this,f={search:!0,filters:{tagList:!0,brandList:!0,place:!0,year:!0,rank:!0,votes:!0,order:!0,orderBy:!0}};this.postAd=function(b,c,d){a.post("/ad",b).success(c)};this.getAds=function(b,c,d){a.get("/ad",{params:b}).success(c)};this.rate=function(b,c,e,f){a.post("/ad/"+b+"/rate",$.param({rank:c}),d.getPostHeader()).success(e)};this.getSearchOptions=function(){var a={};$.extend(!0,a,f,c.current.$$route.adSearchOptions);
return a};this.getAdsByUrl=function(b,c){var f=d.getTranslatedUrl(),m=e.search()||{};a.get(f,{params:m}).success(b)};this.getPossibleTags=function(b,c){a.get("/tag").success(b)};this.getPossibleBrands=function(b,c){a.get("/brand/sm").success(b)};this.fetchPossibleBrands=function(a){b.getPossibleBrands(function(b){a.resolve(b)},function(b){a.reject(b)})};this.fetchPossibleTags=function(a){b.getPossibleTags(function(b){a.resolve(b)},function(b){a.reject(b)})};this.fetchWistiaProjectId=function(b,c,
d){a.get("/brand/"+b+"/wistiaproject").success(c)};this.postBrandAd=function(b,c,d,e){a.post("/brand/"+b+"/ad",c).success(d)};this.changeState=function(b,c,e,f){a.post("/ad/"+b+"/state",$.param(c),d.getPostHeader()).success(e)};this.reportAbuse=function(b,c,e,f){a.post("/ad/"+b+"/report",$.param({message:c}),d.getPostHeader()).success(e)}}]);app.service("CompanyService",["$http","$location","CommonFunctions",function(a,c,e){this.register=function(c,b,e){a.post("/company",c).success(b).error(e)};this.activateCompany=function(c,b,e){a.get("/company/"+c+"/activate").success(b)};this.fetchUserCompanies=function(c,b,e){a.get("/user/"+c+"/company").success(b)};this.fetchCompanyBrands=function(c,b,e){a.get("/company/"+c+"/brand").success(b)};this.fetchBrands=function(c,b){a.get("/brand").success(c)};this.fetchBrand=function(c,b,e){a.get("/brand/"+
c).success(b)};this.registerBrand=function(c,b,e,g){a.post("/company/"+c+"/brand",b).success(e)};this.updateBrand=function(c,b,e,g){a.post("/brand/"+c,b).success(e)};this.getBrandStats=function(c,b,f,g){a.post("/brand/"+c+"/stats",$.param(b),e.getPostHeader()).success(f)}}]);app.service("ContestService",["$http","$location","CommonFunctions",function(a,c,e){this.getContestsByUrl=function(d,b){var f=e.getTranslatedUrl(),g=c.search()||{};a.get(f,{params:g}).success(d)};this.fetchContest=function(c,b,e){a.get("/contest/"+c).success(b)};this.registerContest=function(c,b,e,g){a.post("/brand/"+c+"/contest",b).success(e)};this.updateContest=function(c,b,e,g){a.post("/contest/"+c,b).success(e)};this.registerAnswer=function(c,b,f,g){a.post("/contest/"+c+"/answer",$.param(b),e.getPostHeader()).success(f).error(g)};
this.getAnswers=function(c,b,e){a.get("/contest/"+c+"/answer").success(b)};this.updateWinner=function(c,b,f,g,h){a.post("/contest/"+c+"/answer/"+b+"/state",$.param({winner:f}),e.getPostHeader()).success(g)}}]);app.service("UserService",["$http","$route","$location","CommonFunctions",function(a,c,e,d){this.fetchUserProfile=function(b,c,d){a.get("/user/"+b+"/profile").success(c)};this.activateUser=function(b,c,d){a.get("/user/activate/"+b).success(c)};this.recoverPassword=function(b,c,e){a.post("/user/password/recover",$.param({mail:b}),d.getPostHeader()).success(c)}}]);
/** 
@ignore
**/